### ISSUE TITLE
Is there a guide to use header encryption option

### ISSUE THREAD

**Issue by muziling** [ntop/n2n#1002]
server run command:
```
supernode -p 10086 -v -f -c /root/c.list
```
c.list content:
```
n2n
```

client run command:
```
edge -c n2n -l 192.168.1.10:10086 -k testpwd -H
```

can not obtain ip from server, stuck at:
```
24/May/2022 16:07:01 [edge.c:1222] send REGISTER_SUPER to supernode [192.168.1.10:10086] asking for IP address
```

**Comment by Logan007** [comment]
You will find [information](https://github.com/ntop/n2n/blob/dev/doc/Communities.md#header-encryption) and [details](https://github.com/ntop/n2n/blob/dev/doc/Crypto.md#encryption) in the project's `doc/` folder.

The command lines look good to me. You can use `-vvvvv`to generate more verbose output (at edge as well as on supernode).

Commonly known pitfalls with header encryption are that
- supernode and edge side need to be of same version,
- no previously unencrypted connection attempt (without `-H`) may have been tried (because supernode determines header encryption per community on first connection attempt and sticks with this unencrypted/encrypted decision, restart supernode helps it), and 
- clocks of the systems need to be in sync (+/- 8 secondes allowed max.)

Does it work without header encryption?

If the issue persists, please try (just for the test) to use local edge and supernode (`-l 127.0.0.1:10086`) and see if they can connect.

**Comment by ywnsya** [comment]
I tested it
and I found that：

Supernode| Edge version: n2n v.3.1.1-16
I have already added -c to my supernode
and change the system clock.
However,
-H still can not be used ,It will show “supernode not responding, now trying”
and i added -v in edge , it tells me "DROP packet before first registration with supernode"

Then i suddenly released what will happen when i use -H without Federation?
I edited the supernode.config in the supernode
and turn off all the Federation

Then
My edge connected to the Supernode successfully!

SO is this a problem that I can not use header encryption in federation?

**Comment by Logan007** [comment]
Interesting observation, I will check!

I remember that we did extensive testing with federated supernodes when using user authentication `-I` and `-J`, which basically is "Header Encryption Level 2", but never saw this.

 `DROP packet before first registration with supernode` is just means that it waits for proper registration before allowing data packets, it could be related to auto IP addressing as well. Do you use `-a ...`?

**Comment by ywnsya** [comment]
> Interesting observation, I will check!
> 
> I remember that we did extensive testing with federated supernodes when using user authentication and , which basically is "Header Encryption Level 2", but never saw this.`-I``-J`
> 
> `DROP packet before first registration with supernode` is just means that it waits for proper registration before allowing data packets, it could be related to auto IP addressing as well. Do you use ?`-a ...`

Of cause， i used -a to assign an IP address in both times/tests (which is my habit :) )

My test is very amateurish and not rigorous. Thank you very much for your time to check this problem~

**Comment by Logan007** [comment]
What exactly did you change to make it work? You only removed the `-F` but left the `-l <other supernode>`, right?

**Comment by ywnsya** [comment]
> What exactly did you change to make it work? You only removed the `-F` but left the `-l <other supernode>`, right?

In fact, I removed ALL the "-l" and the  "-F"  as well
