### ISSUE TITLE
The ip and mac address conflict, indicating that the ip already exists, but the ip is not used

### ISSUE THREAD

**Issue by shuncon** [ntop/n2n#1080]
This happens when happynet is installed on win2008 server R2 system and static ip and encry key are set

My n2n service node does not run an edge node, but it does not prevent me from networking. After installing n2n, I only set the port of the service node. Others are not set. The ip of each server is manually set by me and does not exist. The problem of ip conflict, how should I troubleshoot it?

Looking forward to your answer, thank you

27/Feb/2023 15:23:19 [edge_utils.c:2569] ERROR: authentication error, MAC or IP address already in use or not released yet by supernode
27/Feb/2023 15:23:23 [edge_utils.c:2569] ERROR: authentication error, MAC or IP address already in use or not released yet by supernode
27/Feb/2023 15:23:27 [edge_utils.c:2569] ERROR: authentication error, MAC or IP address already in use or not released yet by supernode
27/Feb/2023 15:23:31 [edge_utils.c:2569] ERROR: authentication error, MAC or IP address already in use or not released yet by supernode

**Comment by Logan007** [comment]
Hello,

I am not sure what exact modifications the happynet version includes. But as a general advice, you could try waiting 90 to 120 seconds (to make sure it is not caused by previously exiting improperly, see [here](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#the-edge-repeatedly-throws-an-authentication-error-mac-or-ip-address-already-in-use-or-not-released-yet-by-supernode-message-what-is-wrong)).

On the supernode side, there also is a way to bypass this protection scheme using `-m`.
