### ISSUE TITLE
MTU problems

### ISSUE THREAD

**Issue by emanuele-f** [ntop/n2n#123]
The n2n connection stalls with the current mtu. Manually setting the mtu to 1300 with `ifconfig n2n0 mtu 1300` solves the issue, so default mtu may be too high

**Comment by emanuele-f** [comment]
This seems a bug in the supernode side, need to investigate

**Comment by Logan007** [comment]
In this context, I just want to share the following experience: In one scenario I was working on, ssh did not  connect over n2n. I found that it was due to packet fragmentation caused by some MTU on the path being too low (a known ssh-issue – ssh just does not like to have the cipher list fragmented during handshake;  can be solved by shortening that list by explicitly declaring the cipher to use, e.g. `-c aes128-ctr` on cli).

Just a thought: Could the MTU of the regular network interfaces (which forward the encrypted and thus bigger n2n-packets) of the edges and the supernode have an impact on fragmentation?

**Comment by emanuele-f** [comment]
Yes, this is the reason why the n2n interface MTU is set to a lower value (currently 1400, DEFAULT_MTU in https://github.com/ntop/n2n/blob/dev/n2n.h#L167) rather then the standard 1500 B. If we don't want packets to be fragmented by the "internet" interface, 1400 + sizeof(max_n2n_headers_size) should be <= of the internet interface MTU.

**Comment by lucktu** [comment]
Yes, if MTU is too large, it may not be able to connect. If it is too small, the efficiency will be low. For example, I have set 1328 in Windows.

Can it be automatically identified and set? ^_^

**Comment by emanuele-f** [comment]
The intent is to set the proper MTU automatically but if you experince the said problems than something is not working properly. Is 1328 the maximum value which does not give you issues?

**Comment by lucktu** [comment]
Yes, it's the maximum value. but then again, automation may not work.

**Comment by lucktu** [comment]
Today, I checked the MTU on the padavan router and found that tinc is 1500, and n2n is the default 1400.

So I changed some n2n's MTU to 1500, and then used ftp to transmit data. In the case of 1400, it was 1.2 MB/s, and 1500 was 1.3 MB/s. I had done many such tests. 

![image](https://github.com/lucktu/other/raw/master/image/speed/19071401.PNG)

In particular, I set the MTU to 1600. I can actually communicate. ping and ftp can be used, but the speed feels similar to that of the MTU when it is 1400. Because it's beyond common sense, and I 've only done it once.

Strangely enough, zerotier's MTU is 2800!

**Comment by Logan007** [comment]
That's really strange... using `tracepath <some_server>`, I usually get a `pmtu 1492` at some point/server which therefore would be the optimum to use in the internet.

Sizes below wouldn't use the optimum packet size (1300 instead of 1492 would explain the corresponding drop very well). Sizes above would result in fragmentation of packets, explaining that decrease in throughput.

**Comment by lucktu** [comment]
Use 1492 to win weakly, my networkes (edge A & B) are all PPPoE dial up (it's 1492).
You can think of it as the same.

![image](https://github.com/lucktu/other/raw/master/image/speed/19071501.PNG)

**Comment by emanuele-f** [comment]
MTU for AES should be fixed in 035b66b1a997418293f82e663ed7b74ca0d2c143 , the twofish version should be already correct

**Comment by lucktu** [comment]
R216 Increase 0.2 MB/s relative to r198 speed (1.348 --> 1.571 MB/s, Now MTU is 1390).

![image](https://github.com/lucktu/other/raw/master/image/speed/19071601.PNG)

Thank you very much!

**Comment by emanuele-f** [comment]
I'm still debugging this as it seems like packets with some sizes near the MTU are dropped

**Comment by lucktu** [comment]
That's weird: MTU 1400 is the worst again!
![image](https://github.com/lucktu/other/raw/master/image/speed/19071602.PNG)

**Comment by okoddcat** [comment]
Hi @emanuele-f ,

I also encountered this issue when I was trying to SSH to a remote edge node inside a docker container, the docker image is based on debian:stable-slim. You can search the keywords `ssh expecting SSH2_MSG_KEX_ECDH_REPLY` to get more inforamtion. Hope this will help you.

Thanks,
Martin

**Comment by emanuele-f** [comment]
@mtanneb my ssh client also blocks on SSH2_MSG_KEX_ECDH_REPLY .

The problem is caused by an improper handling of PMTU discovery by my ISP as described in https://en.wikipedia.org/wiki/Path_MTU_Discovery#Problems . I've adopted a more conservative approach in 6c67ed044036c5268295fceb5c8dbb2c8ecc5b73 by setting a lower default MTU value and also disable PMTU discovery on the socket to avoid stall. https://github.com/ntop/n2n/blob/dev/doc/MTU.md contains a full description of the issues. @lucktu can you confirm that this does not provide visible slowdowns ?

Todo for me: disable PMTU discovery on other platforms

**Comment by lucktu** [comment]
The two routers (padavan, MTK 7620/7621,PPPoE) are under the same optical fiber modem.
edge -d aa -a 10.2.0.100 -c 123 -k test -l n2n.lucktu.com:10086 -M 1400 &
edge -d bb -a 10.3.0.100 -c 456 -k test -l n2n.lucktu.com:10086 & 
![image](https://github.com/lucktu/other/raw/master/image/speed/19081701.png)

again (100M)
![image](https://github.com/lucktu/other/raw/master/image/speed/19081702.png)

again (100M)
![image](https://github.com/lucktu/other/raw/master/image/speed/19081703.png)

more (100M)
mtu:1386 2.10s-0.77 MB/s
mtu:1388 2.05s-0.80
mtu:1390 2.08s-0.78
mtu:1392 2.05s-0.80
mtu:1394 2.05s-0.80

mtu:1394 2.03s-0.81
mtu:1396 2.00s-0.83
mtu:1398 2.04s-0.81
mtu:1400 2.03s-0.81
mtu:1402 2.02s-0.82

mtu:1402 2:59s-0.56
mtu:1452 2:23s-0.70
mtu:1500 2:19s-0.72
mtu:2800 2:21s-0.71

**Comment by emanuele-f** [comment]
Thank you, results look fine

**Comment by emanuele-f** [comment]
PMTU now also disabled on windows in 0538c5261d7db6a5022dce87852ebb6b7ec876f4
