### ISSUE TITLE
Does n2n encrypt all the traffic?

### ISSUE THREAD

**Issue by gongzhang** [ntop/n2n#124]
Does n2n encrypt the traffic between super and edge?

**Comment by emanuele-f** [comment]
Yes. If you specify the `-k` option, it will encrypt the traffic. Only the edge nodes of the same community can decrypt the data, the supernode can't because it does not know the key. However, some metadata information (like the community in use and IP address of the peers) is sent in clear so that the supernode can do the forwarding

**Comment by gongzhang** [comment]
Thank you @emanuele-f :)
