### ISSUE TITLE
WARNING: Supernode not responding, now trying 111.254.11.109:50001

### ISSUE THREAD

**Issue by Inspironsputid** [ntop/n2n#181]
hey
supernode getting time out and nods unable to connect with edge

**Comment by Xeath** [comment]
Maybe your ISP has disabled the udp protocol.

**Comment by emanuele-f** [comment]
Did it ever worked in the past? Maybe you need to port forward the supernode port?

**Comment by emanuele-f** [comment]
@Inspironsputid any news on this?

**Comment by yanggis** [comment]
@emanuele-f I also have such issue; the problem happened after 20-30 hours with heavy traffic. If I restart the edge node service, everything becomes normal again.

**Comment by emanuele-f** [comment]
Are you using the latest n2n version from github, dev branch?

**Comment by yanggis** [comment]
@emanuele-f based the code released on 14 Nov 2019, not the latest one.

**Comment by yanggis** [comment]
@emanuele-f I've upgraded to the latest version, but unfortunately, the issue persists.

**Comment by emanuele-f** [comment]
Can you provide a PCAP file containing the traffic to/from the supernode? E.g. `sudo tcpdump -i eth0 -n -s0 -w sn.pcap host 1.2.3.4` where `eth0` is the internet interface and `1.2.3.4` is  the IP address of the supernode?

**Comment by yanggis** [comment]
@emanuele-f thanks for your response. when the network is down, I cannot find any packet; if I restart the edge0 interface, everything is normal again. This event only happens on two servers behind NAT network.

**Comment by Logan007** [comment]
I have experienced a similar issue on one of my edges which is (at least) double-NATed. I am not sure if this happens when some of the in-between-the-NATs network configuration or external address is changed by ISP.

The edge repeatedly tries to connect claiming the supernode were not available. `ping supernode` works fine and a restart of `edge` solves the problem. 

It "_feels_" a bit like the edge's socket is still stuck with the original external _path_ or _socket_ (sorry for the wording, my network-related vocabulary is limited :wink:) while the real-world one or somewhere in-between-the-NATs has already changed and the edge just does not become aware of it.

So, what I am trying now are the following changes: Every time a "Supernode is not responding" occurs in `update_supernode_reg()` , `edge_init_sockets()` gets called to re-initialize the sockets. To do so in a proper way, `edge_init_sockets()` is prepended by some (guarded) calls to `closesocket()` in order to close any open sockets before opening them (again).

Let's see how this works out and if it helps increasing stability. I will report back.

Any thoughts?

_P. S._ Maybe, only the way back from supernode to edge is affected (_listen socket assignment between the NATs_). It would be interesting to find out if that edge was still registered with the supernode, i.e. if the REGISTER_SUPER got through. Unfortunately, I did not check whenever this has happened.

**Comment by Logan007** [comment]
I think I can confirm this _bug_ or _behaviour_. It happens almost always in that (at least) double NATed scenario (most likely, it is triple-NATed or even more) whenever the ISP was changing the external public IP. Not sure if it is ISP-specific or somehow related to one of the in-between NATs or their communication behaviour.

However, the above drafted solution seems to prevent it. I will provide a pull request somewhen during the next days.

I just hope that closing and re-opening the sockets is not considered violent and that it does not interfere with access rights or so.
