### ISSUE TITLE
Can i monitor n2n with ntopng?

### ISSUE THREAD

**Issue by mrbluecoat** [ntop/n2n#185]
Sorry for the noob question, but if I set up a n2n remote connection to my home network and my home network is monitored with ntopng/nDPI can I monitor that activity or will the encryption interfere?  Is there built-in support for that type of monitoring?

**Comment by emanuele-f** [comment]
Can you create a diagram of your setup? Are you willing to detect/decapsulate n2n traffic in ntopng/nDPI or just account the traffic for the total bandwidth? Please also check out https://github.com/ntop/n2n/blob/dev/tools/n2n_decode.c which can decode n2n traffic

**Comment by mrbluecoat** [comment]
My use case is monitoring site access when my kids' smartphones are on cellular versus WiFi.  I'm setting up their phones to connect via VPN to our home network where ntop can log their activity just like when they're on WiFi.

**Comment by emanuele-f** [comment]
If you are using hin2n in android please note that you will need this pull request in order to set up the default gateway: https://github.com/switch-iot/hin2n/pull/13

When using the VPN, all the phone traffic will reach the gateway inside the vpn (an edge node with a virtual n2n0 interface). In this case you can monitor the plain traffic just by running ntopng on that interface (e.g. `ntopng -i n2n0`).

If you just want your kids to surf safe, you can use a child filtered DNS https://www.leowkahman.com/2017/09/11/enforce-safe-search-on-google-youtube-bin . At ntop we've also developed a little firewall system which runs on raspberry with content filtering, if you are interested for a trial contact us https://www.ntop.org/support/need-help-2/contact-us

**Comment by mrbluecoat** [comment]
Thanks for the link to hin2n, which is closer to my goal.

The https://www.leowkahman.com/2017/09/11/enforce-safe-search-on-google-youtube-bing/ guide is great but I'd prefer not to root the smartphone to edit the hosts file and it's trivial for my teenagers to [hard code their DNS server to Google's unfiltered 8.8.8.8](https://forum.xda-developers.com/general/xda-university/guide-how-to-change-dns-android-device-t3273769).

Regarding your last point, I'm assuming you're referring to nEdge which indeed would be ideal and I didn't know it could run on raspberry-grade hardware but the Pro price is a bit steep (I'd just go for Gryphon Homebound at that point).  

Thanks again for the pointers!

**Comment by emanuele-f** [comment]
Using hin2n you would not need to root the phone to change the DNS server, but sadly that feature is not implemented yet in the official app. Actually we've built from the ground up a very small firewall sw which does fewer things than nEdge but can run on SBC without problems.

**Comment by mrbluecoat** [comment]
Cool, sent contact via the form you provided.
