### ISSUE TITLE
How to set up a windows firewall

### ISSUE THREAD

**Issue by andsontan** [ntop/n2n#201]
Edge 10 won't work on win10, but it works after closing windows defender。

**Comment by emanuele-f** [comment]
Please give us more info about what you mean with `Edge 10` and what is your n2n configuration. n2n usually opens a connection to a remote supernode, so it should not be blocked by the firewall (it is an outgoing connection). If you identify the problem, you can also add an exception for a specific port instead of disabling the firewall all together

**Comment by emanuele-f** [comment]
Any news?
