### ISSUE TITLE
Bridge support?

### ISSUE THREAD

**Issue by pishitlab** [ntop/n2n#204]
Hello

I have run edge node on 2 server. I can ping between node. I try to create bridge via brctl command.

> edge -h
> Welcome to n2n v.2.5.1.r247.d8871c2 for x86_64-unknown-linux-gnu
> Built on Mar  2 2020 12:00:25
> Copyright 2007-19 - ntop.org and contributors

Node1
> edge -d tap0 -c pi-network -k kodfma0-2lkmdfv -M 1500 -a 192.168.100.1 -f -l 127.0.0.1:1234
> brctl addbr br0
> brctl stp br0 on
> ip addr flush dev tap0
> brctl addif br0 tap0
> ip addr add 192.168.10.10/24 dev br0
> ip link set dev br0 up

Node2
> edge -d tap0 -c pi-network -k kodfma0-2lkmdfv -M 1500 -a 192.168.100.1 -f -l node1:1234
> brctl addbr br0
> brctl stp br0 on
> ip addr flush dev tap0
> brctl addif br0 tap0
> ip addr add 192.168.10.20/24 dev br0
> ip link set dev br0 up

On any node with bridge I can't ping between node. Please help me.

**Comment by emanuele-f** [comment]
Can you describe the setup you are trying to implement?

**Comment by emanuele-f** [comment]
Any news?

**Comment by ep0me0** [comment]
I have the same question.
My scenario: integrate the edge0 interface into a Linux virtual bridge such that a VM connected to another TAP on this bridge can communicate across the n2n link with a VM on the peer that has the same setup.
It works fine in a routed setup (i.e., the bridge is separate from the edge0 interface and Linux routing is enabled between them), but I need L2 protocols between the two VMs.
Is there any way to get a bridged setup to work? Thank you in advance!

**Comment by emanuele-f** [comment]
The network created by n2n is already a L2 virtual network, so why do you need an additional linux bridge? Can you provide a diagram to better illustrate the setup?

**Comment by ep0me0** [comment]
Thank you for your answer. The setup is hopefully shown in the attached diagram. The VM in the diagram runs a legacy OS that needs a L2 connection to another VM on a second Linux host. I'm looking for a way to add the VM to the L2 network created by n2n.
![n2n-diagram](https://user-images.githubusercontent.com/66648942/84134159-77a6aa80-aa48-11ea-955d-30510681d65c.png)

**Comment by ep0me0** [comment]
Additional information: if I 
- remove the IP address from edge0,
- map edge0 directly to the VM, and
- set MAC address and IP address inside the VM to be identical to what was configured for edge0,
the two VMs can communicate. 
However, there is - of course - no communication between Linux and the VMs, because Linux no longer belongs to the n2n subnet.

**Comment by skyformat99** [comment]
I have the same question.
It would be very convenient to have bridge support.

**Comment by emanuele-f** [comment]
Your setup is still not very clear to me. Anyway, supposing that you have set up a linux bridge br0 on the host with two network interfaces tap0 (connected to the vm1) and tap1 (connected to the vm2), you start n2n on the host and it creates edge0 . In order to use n2n on the bridge the following should work:

1. Add the edge0 interface to br0, so now br0 bridges together edge0, tap0 and tap1
2. Remove the IP address on the edge0 interface `ip addr delete ...`
3. Set the IP address on the br0 interface instead `ip addr add ... dev br0`

Now the L2 traffic of the tap0 and tap1 interfaces should reach the remote connected edges via the edge0 interface

**Comment by ep0me0** [comment]
Sorry that my description was not clear. I will test your suggested steps and report my results here.

**Comment by ep0me0** [comment]
![Screenshot from 2020-06-12 16-28-12](https://user-images.githubusercontent.com/66648942/84513465-bf883480-acc9-11ea-9a40-07c1be8d0dd8.png)

The edge process is started with the command (host2 example):
edge -E -r -a 10.1.2.2 -k abc -c mynet -l  supernode:1200
No luck, unfortunately. I hope the above illustrates a bit better what I was attempting to do.

**Comment by emanuele-f** [comment]
Sorry for the late reply. I think I can reproduce the issue. The problem in my case is on the supernode, which is visible by enabling the debug log (`supernode -vv`):

1. The ARP request with source mac address M1 from the TAP interface successfully reaches the remote peer
2. The ARP reply from the remote peer is transmitted to the supernode, with destination mac address M1
3. The supernode looks up M1 in his hash table but does not find it, so it print a debug message `try_forward unknown MAC` and drops the packet

The problem is that the supernode records the MAC address of the peers only during the REGISTER_SUPER packet, which occurs when the edge node connects to the supernode (see `update_edge`). Instead we also need to remember the MAC addresses seen on the routed traffic of the peers.

**Comment by Logan007** [comment]
Are you talking about the internal real adapter's MAC addresses?

**Comment by emanuele-f** [comment]
Yes, in the linked use case there is an additional TAP interface connected to a bridge interface and to the actual edge interface. The mac address written into the packet sent via the TAP is the mac of the TAP interface, which is different from the registered edge mac address

**Comment by Logan007** [comment]
So, maybe the REGISTER datagram needs some payload after all…

This feature should be used with caution as I would not like to see my physical adapters' MAC addresses being sent out by accident. It should assuredly be restricted to artificially made-up MACs.

**Comment by ep0me0** [comment]
Thank you very much for your analysis of the problem. It would be great, if n2n could be made to work with such a bridge configuration.

**Comment by emanuele-f** [comment]
> Thank you very much for your analysis of the problem. It would be great, if n2n could be made to work with such a bridge configuration.

Can you check if https://github.com/ntop/n2n/pull/303 works for you too?

**Comment by ep0me0** [comment]
I will test and get back to you.

**Comment by ep0me0** [comment]
I tried the patched version and unfortunately, I still cannot get it to work. See output below.
My supernode is on the same host as edge 1 - can this cause a problem?
Any other debug I can turn on to identify the problem?

- Setup is same as in comment above in this thread.
- Ping-attempt host2 to vm1
3E:BB:42:59:90:95 = br0 and edge0 of host2
F2:74:D2:5F:51:B2 = tap0_br0 on host1

Supernode -vv output:

06/Jul/2020 07:48:01 [sn.c:452] Processing incoming UDP packet [len: 132][sender: xxx.xxx.xxx.xxx:57327]
06/Jul/2020 07:48:01 [sn.c:570] RX PACKET (unicast) 3E:BB:42:59:90:95 -> F2:74:D2:5F:51:B2 local
06/Jul/2020 07:48:01 [sn.c:230] try_forward unknown MAC: F2:74:D2:5F:51:B2
06/Jul/2020 07:48:02 [sn.c:452] Processing incoming UDP packet [len: 132][sender: 172.31.37.66:57327]
06/Jul/2020 07:48:02 [sn.c:570] RX PACKET (unicast) 3E:BB:42:59:90:95 -> F2:74:D2:5F:51:B2 local
06/Jul/2020 07:48:02 [sn.c:230] try_forward unknown MAC: F2:74:D2:5F:51:B2

**Comment by emanuele-f** [comment]
Can you confirm that both the edge nodes are using the patched code (https://github.com/emanuele-f/n2n/tree/switched_traffic2)? Can you post the output log of the edges while running them with the -vv option?

**Comment by ep0me0** [comment]
Both edge nodes run with the patched code. 
I will collect the log output and post the result.

**Comment by ep0me0** [comment]
Here are the edge logs:
[edge-logs.zip](https://github.com/ntop/n2n/files/4883935/edge-logs.zip)

**Comment by emanuele-f** [comment]
Edit: before going on with the tests, please add the `-S` option to the edge nodes so that we know that the issue is not linked to P2P issues.

Ok so you are pinging the vm2 with MAC address `f2:ef:ec:ae:0b:2c` from host1:

1. host1 sends a broadcast ARP request "who has 10.1.2.20"
2. host2 sends an ARP reply: "10.1.2.20 is at f2:ef:ec:ae:0b:2c"
3. host1 receives the ARP reply and it now knows that it can reach vm2 via the host2 edge node: `New switched MAC: F2:EF:EC:AE:0B:2C via 6E:7A:16:32:37:2F`
4. host1 sends the ICMP request packet via `6E:7A:16:32:37:2F`: `find_peer_address (6E:7A:16:32:37:2F) -> [xxx.xxx.xxx.108:55442]`

You should try to capture the packets on `edge0` on the *host2* and see if the ICMP requests are properly received there:

- If you can see the ICMP request on edge0, it means that the packets are dropped internally by linux on the host2
- If you cannot see the ICMP request packets, please perform a tcpdump to capture the UDP packets going to the supernode (the filter `udp and port 1200` should be fine in your case) and see what's going on (you can use https://github.com/ntop/n2n/tree/dev/wireshark to dissect the packets).

The supernode should never see the `F2:EF:EC:AE:0B:2C` MAC address as it only see `6E:7A:16:32:37:2F`.

**Comment by ep0me0** [comment]
Thank you for your help. I will test this and report the results here.

**Comment by ep0me0** [comment]
I started my configuration from scratch with the -S setting and everything seems to work (vm1 and vm2 can reach each other). I have not yet been able to figure out what went wrong with the previous configuration. Should I have new/additional information, I will report it here.

**Comment by uosbox** [comment]
I had the same problem. An edge node is bridged in the br LAN of openwrt, and the edge node provides DHCP service. The other edge node can get the IP address assigned by DHCP, but Ping fails

**Comment by uosbox** [comment]
@emanuele-f Hello! Use #303 patch, still can't bridge! No version of n2nv2 supports bridging, but n2nv1 can bridge normally.

**Comment by uosbox** [comment]
> Hello
> 
> I have run edge node on 2 server. I can ping between node. I try to create bridge via brctl command.
> 
> > edge -h
> > Welcome to n2n v.2.5.1.r247.d8871c2 for x86_64-unknown-linux-gnu
> > Built on Mar  2 2020 12:00:25
> > Copyright 2007-19 - ntop.org and contributors
> 
> Node1
> 
> > edge -d tap0 -c pi-network -k kodfma0-2lkmdfv -M 1500 -a 192.168.100.1 -f -l 127.0.0.1:1234
> > brctl addbr br0
> > brctl stp br0 on
> > ip addr flush dev tap0
> > brctl addif br0 tap0
> > ip addr add 192.168.10.10/24 dev br0
> > ip link set dev br0 up
> 
> Node2
> 
> > edge -d tap0 -c pi-network -k kodfma0-2lkmdfv -M 1500 -a 192.168.100.1 -f -l node1:1234
> > brctl addbr br0
> > brctl stp br0 on
> > ip addr flush dev tap0
> > brctl addif br0 tap0
> > ip addr add 192.168.10.20/24 dev br0
> > ip link set dev br0 up
> 
> On any node with bridge I can't ping between node. Please help me.

Hello! Have you solved your problem? How to solve it! I have the same problem! Ping of the interface placed in the bridge failed.

**Comment by emanuele-f** [comment]
> Hello! Have you solved your problem? How to solve it! I have the same problem! Ping of the interface placed in the bridge failed.

Rather than applying the patch manually try to use my branch https://github.com/emanuele-f/n2n/tree/switched_traffic2 for both the supernode and the two edge nodes so that we can be sure that there are no new incompatibilities introduced since then in the official n2n. You can also enable the debugging on the supernode with the `-vv` option and report the output as explained in my comments above.

**Comment by uosbox** [comment]
> > Hello! Have you solved your problem? How to solve it! I have the same problem! Ping of the interface placed in the bridge failed.
> 
> Rather than applying the patch manually try to use my branch https://github.com/emanuele-f/n2n/tree/switched_traffic2 for both the supernode and the two edge nodes so that we can be sure that there are no new incompatibilities introduced since then in the official n2n. You can also enable the debugging on the supernode with the `-vv` option and report the output as explained in my comments above.

Thank you for your reply! No direct use of switched_ Traffic2 compilation is due to the need for some new features of n2n-2.8. I use it https://github.com/emanuele-f/n2n/tree/switched_ The traffic branch is changed because https://github.com/emanuele-f/n2n/tree/switched_ Traffic2 branch does not match the modification of n2n-2.8

**Comment by emanuele-f** [comment]
The first step for this troubleshooting is to ensure that you are using the exact n2n branch that both ep0me0 and I confirmed as working. So I suggest you to use the switched_traffic2 branch and make it work, only then you can focus on porting the patch on n2n-2.8
