### ISSUE TITLE
Now do you need -m to avoid MAC address conflicts?

### ISSUE THREAD

**Issue by woOzZ2** [ntop/n2n#205]
If there is no -m parameter, will there be MAC conflict? Is there any improvement?Previous versions seem to conflict
By the way, is the edge-r parameter the same as net.ipv4.ip_forward = 1?

**Comment by emanuele-f** [comment]
If the `-m` parameter is not specified, a random MAC will be chosen. Please use the dev version which has many improvements over the stable one. The `-r` parameter is similar in functionality to the `net.ipv4.ip_forward`

**Comment by Logan007** [comment]
While `...ip_forward` is for the kernel to (re)distribute packets from other subnets to the correct interface, `-r` allows the n2n-link to accept those packets for further forwarding (otherwise ignored), thus link-specific.  In other words: `-r` is an additional requirement to the `...ip_forward` if you plan to forward packets via  the n2n-link.
