### ISSUE TITLE
Bug in n2n.h file.

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#252]
error  line  :
#include <openssl/opensslv.h>
#include <openssl/crypto.h>

The correct ones are as follows:

#ifdef  N2N_HAVE_AES
#include <openssl/opensslv.h>
#include <openssl/crypto.h>
#endif

**Comment by Logan007** [comment]
Good catch! Are you able to provide a corresponding pull request?

**Comment by skyformat99** [comment]
> Good catch! Are you able to provide a corresponding pull request?

I am not familiar with Git, can you help me provide a corresponding pull request?

**Comment by Logan007** [comment]
I so feel your pain... I remember well myself being fat-fingering with git... and still am far from being git-savvy. Anyway:

You probably have your own fork of n2n. It should be really "fresh". To get it up to date, I found [this](https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date) description extremely useful – I use it everytime because I am not able to remember all the steps.


(( The following steps (+/-) are also explained [here](https://github.com/firstcontributions/first-contributions).  ))

As soon as you have performed these steps for a "fresh" local (on your computer) and "remote" (on github) fork, you need to create a new _branch_ for your new feature or fix:

`git branch myNewFeature`

Then, you need to switch to that _branch_. Git-speech is _checkout_:

`git checkout myNewFeature` 

You can always check on what branch you are, it is just:

`git branch`

Then, you can start editing `n2n.h` and/or other files. You should only edit the lines for that specific feature you want to change (otherwise, it best would make another pull request).

When you are done with editing, compiling, and testing, you need to _add_ the file(s) you have changed to the so called _index_ – that is the virtual place to concentrate all files, that are about to be summarized into one _commit_. So, for each file you have changed:

`git add filenameOfTheFileYouHaveChanged`

Up to now, you can easily change files again. Just _add_ them again.

After having _added_ the files, you put it together to one _commit_:

`git commit -m "myShortMessageOnWhatIDid"`

You have to put the quotes. This _commit_ needs to be _pushed_ to your (!) – not ntop's – fork:

`git push`

If this went well, you can use the browser to press the newly appearing button "Compare & _Pull Request_" to offer the changes of this _branch_ as _pull request_. If you are signed in on github, the button should automatically appear for example on ntop's n2n page. Just add a short description of your _pull request_ and you should be done...
