### ISSUE TITLE
It is recommended to add key option for supernode

### ISSUE THREAD

**Issue by small-5** [ntop/n2n#257]
Add a key option for the supernode, use the same cipher suite as the edge for authentication, and encrypt the virtual MAC address, virtual IP, and community name to avoid clear text display. Also added a key option for supernode authentication on the edge.

**Comment by Logan007** [comment]
Thank you for your suggestion.

As for the **encryption**, this is already being implemented, please have a look at #198. Is it what you were having in mind?

As for the **authentication**, it relies on _knowing-the-key-and-community_, as neither edges nor supernode keep a directory of nodes or PKI. Do you have an idea on how this could be realized?

**Comment by small-5** [comment]
Thank you for your reply.
I mean set a key and cipher suite on the supernode, and also set another key on the edge (not the existing -k parameter). Use this key and cipher suite (Can be the same parameter as edge's existing cipher suite) exchange with supernode, if the authentication is passed, add the edge to the community, and use this key and cipher suite to encrypt the virtual MAC virtual IP community name and other plaintext information.

**Comment by small-5** [comment]
For example, the cipher suite set by edge is chacha20, and then the authenticated key is sent to supernode by using chacha20 encryption. Supernode is decrypted by the preset cipher Suite (assuming it is also chacha20). If the key is the same, it is authenticated. edge's cipher suite for authentication can use the existing - Ax or set a separate set of parameters.

**Comment by Logan007** [comment]
I see. That is what basically will happen with #198. Only difference is that no extra key required (as community name will be used to keep it simple for the user – never transferred in plain) and authentication happens by knowing the correct key (no extra authentication mechanism required), otherwise no communication. You will find a detailed description in the aforementioned discussion.

Plans are that it will be as easy as adding a simple `-H` (as in **H**eader encryption) to command line parameters of the edges and just update to the newest supernode version. Exisiting networks might also want to change their community name then (as it will be used as key from then on and will have been transferred in plain up to then).

I have already started implementation and I think that it will take me up to two months or so to have it finished – depending on spare-time availability. For that first shot, the cipher for the _outer_, i.e. non-payload, encryption cannot be chosen, it is set to Speck CTR for now (built-in and non-lib thus always available & format-preserving & fast). I want to make it work first of all, the cipher could see a change or extensions later on.

**Comment by small-5** [comment]
Thank you for your reply.
The current key parameters is only used for verification between edges.I hope that the purpose of adding the key to the supernode is to only allow the supernode to be used by the verified edge, so that the same supernode can be used after multiple communities pass the verification.

**Comment by Logan007** [comment]
Yes, it will probably turn out that way. To be specific, only edges that share the same community (then: used as key, never plainly transmitted) with the supernode (it will still be able to serve several, well defined communities) are "allowed" (others' packets couldn't be decrypted and thus discarded) to be used.

Thank you for bringing it up, discussion helps to reflect thoughts on that matter.
