### ISSUE TITLE
where is supernode.conf file after I did a Manual Compilation

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#307]
My action:
./autogen.sh
./configure
make

# optionally install
make install

I know /sbin/supernode and /sbin/edge . But I don't where is the supernode.conf , I just need to create a conf file by myself?

**Comment by Logan007** [comment]
I have not seen a `.conf` file being created by n2n's `Makefile` yet. Given that its use is optional, I guess it is just not generated.

So, if you want to use it instead of command line options, you will have to create it yourself. Syntax is the same as command line options, see [here](https://github.com/ntop/n2n#setting-up-a-custom-supernode) for an example.

**Comment by tlsalex** [comment]
> I have not seen a `.conf` file being created by n2n's `Makefile` yet. Given that its use is optional, I guess it is just not generated.
> 
> 
> 
> So, if you want to use it instead of command line options, you will have to create it yourself. Syntax is the same as command line options, see [here](https://github.com/ntop/n2n#setting-up-a-custom-supernode) for an example.

thanks man

**Comment by lw65** [comment]
it's here  [https://github.com/ntop/n2n/tree/dev/packages/etc/n2n](url)
