### ISSUE TITLE
Question: SNM=yes

### ISSUE THREAD

**Issue by enira** [ntop/n2n#34]
Is it possible to connect two nodes? 
I noticed in the following article: https://aosekai.net/2012/09/how-to-setup-a-decentralized-overlay-network-using-n2n/
the use of -i S1_IP:SNM_PORT, however it does not seem to work and the supernode binary doesn't recognizes the '-i' parameter. Is this still implemented?

**Comment by lucaderi** [comment]
This is a code patch that needs to be merged first in n2n. I need to study the code. Currently a edge can talk to multiple supernodes only

**Comment by struanb** [comment]
A fully decentralised N2N configuration would be really useful. I spent many hours trying to get this code branch working, but didn't manage it.

**Comment by lucaderi** [comment]
In order to avoid specifying in supernodes the list of peers (that is already specified in edges), https://github.com/ntop/n2n/commit/1c7b14995b8a899ec465af3cde8228b30ed437a7 implements multiple supernode registration. This means that when with edge via -l multiple supernodes are specified, the edge will register with all of them and not with the first one as happening so far.

Please check if this is enough for your needs.

**Comment by emanuele-f** [comment]
Please check out #45 for an enhancement / fix
