### ISSUE TITLE
How to know whether p2p punching success? Is it possible to disable supernode forward?

### ISSUE THREAD

**Issue by joshuafc** [ntop/n2n#344]
Greate Project!

How to know whether p2p punching success? Is it possible to disable supernode forward? 

If p2p connection failed,  then keep node unreachable, to save my aws cloud server broadband bill.

**Comment by Logan007** [comment]
> How to know whether p2p punching success?

Please see #208 on how to get further stats including the number of packets sent via p2p vs. through the supernode.

> Is it possible to disable supernode forward?

This is not implemented.

> If p2p connection failed, then keep node unreachable, to save my aws cloud server broadband bill.

I am not completely sure if this would be compatible with the current communication scheme because as far as I can see, first  PACKTETs to so far unknown nodes via a supernode additionally serve to introducing the sending nodes and their p2p sockets. Also, only the supernode will know where to forward the fist packet to (by the help of having the nodes REGISTERed to the supernode).

**Comment by joshuafc** [comment]
thanks! I will close it.

**Comment by Logan007** [comment]
Concerning you second question...

_Is it possible to disable supernode forward?_

... we should continue discussion at #784 to avoid duplicates. Closing it here.
