### ISSUE TITLE
How get the name of the federation 

### ISSUE THREAD

**Issue by fcarli3** [ntop/n2n#435]
Talking about the name of the federation, it could be command-line provided (e.g., `-f <federation name>`) or default to some name (e.g., `***federation***`, maybe using a forbidden character ). The federation would have the `header_encryption` flag enabled by default. 

 We will need a place to store command-line parameter for the federation (to exclude it in `load_communities_from_file()`). So, the `n2n_sn_t` structure must be enhanced by such a field.

Other supernodes later joining that federation need to know the federation name. Moreover, the federation name will be their shared secret used as key

**Comment by Logan007** [comment]
In the `community.list` file, you would find a list of forbidden characters which are not allowed in regular community names because they would form a regular expression. As the regular expressions do not get directly copied to community names, those characters can never appear by accident in regular community names – which is good.

**Comment by fcarli3** [comment]
Ok, so  we should add a specific field to `n2n_sn_t` structure (e.g., `char federation[N2N_FEDERATION_SIZE]`) to store the federation name. 
Then, I don't understand if we should add the federation name to `community.list` file as the federation is a (special) community.
I don't understand also if we need another function to load the federation or we could use `load_allowed_sn_community` with some changes.
Moreover, we should change `setOption` and add a specific flag (`-f` already exists, so idk which one is the best choice)

**Comment by Logan007** [comment]
> Ok, so we should add a specific field to n2n_sn_t structure (e.g., char federation[N2N_FEDERATION_SIZE]) to store the federation name.

I agree. You might want to use N2N_COMMUNITY_SIZE instead, so it always will be handled the same way everywhere, e.g. as community name in the common section of the packets etc.

> Then, I don't understand if we should add the federation name to community.list file as the federation is a (special) community.

No, do not add it to the file. I was saying to have a look at that file because it lists the _not allowed characters_. And then, at least for the default value, i.e. if no `-f` is given, use a federation name which contains at least one of these characters (so no edge can accidentally imitate a federation). That's basically it. You could even think of always prepending such a character, perhaps `*` in front of every federation name, even those given by `-f`: `-f Alliance` could internally be handled as `"*Alliance"`.

> I don't understand also if we need another function to load the federation or we could use load_allowed_sn_community with some changes.

No, the federation could internally be set to some default value during initialization and then get overwritten if some `-f <federation name>` is given.

**Far future** enhancement could include a federation file containing several federations to make one supernode part of several federations (handling several of those special communities internally – if we can handle one, we could handle more). But that might require some more thoughts in detail… Forget about this paragraph for now.

As for the `load_allowed_sn_communities`, I was thinking that it should make sure that none of the loaded communitiy names equals the federation name. But, I was wrong: Using the _not allowed characters_ even for the `-f`-provided federation name, this is not neccessary anymore – work saved!

> Moreover, we should change setOption and add a specific flag (-f already exists, so idk which one is the best choice)

Oh, I see. I must have suppressed. Such a huge enhancement definitely deserves capital letters: Why not use **`-F`** then?

**Comment by fcarli3** [comment]
> Oh, I see. I must have suppressed. Such a huge enhancement definitely deserves capital letters: Why not use -F then? 

Ok, `-F` is perfect. Should we insert also a long options (e.g., `--federation <federation_name>`) or is it unecessary?

> No, the federation could internally be set to some default value during initialization and then get overwritten if some -f <federation name> is given

I have understood that but if federation name is not command-line provided, which part of the code initialize our federation? My understanding is that if there aren't command line options, the program takes default values calling `loadFromFile` function. Is it right?

**Comment by fengdaolong** [comment]
Obviously it is more appropriate to use uppercase -C. Big federation -C, small community -c.🤓

**Comment by Logan007** [comment]
> Should we insert also a long options (e.g., --federation <federation_name>) or is it unecessary?

As you like, it does not take much to implement and does not hurt – but I personally do not use them anyway, so I might the wrong person to ask…

> which part of the code initialize our federation?

The `int sn_init(n2n_sn_t *sss)` function might be a good place to set the federation default name. `-F`¹-handling in `setOption` may overwrite it then. In `main()`, **after** reading from CLI or file (sn.c:496), the (now definitely filled, either default or provided by `-F`) `char federation[N2N_FEDERATION_SIZE]` field content could be converted to that special community, maybe by calling a new function like `int add_federation (n2n_sn_t *sss, char * federation, …)` or so.

> My understanding is that if there aren't command line options, the program takes default values calling loadFromFile function. Is it right?

Yes, the defaults will be set in the `sn_init()` function which gets called right at the beginning of `main()`. And no, that does not happen in the `loadFromFile()` function which gets called a bit later. That's why we should provide a default beforehand, just in case there is no `-F`.

Just one more hint: `load_allowed_sn_community()` deletes all communities upfront. That is a good thing for initialization and also, if called later in the course of the program (this does not happen up to now, but could be implemented maybe by some `reload communities` command at the management port). So, maybe the deletion loop in `load_allowed_sn_community()` should make sure that the federation is not deleted (`if(!(s->is_federation)) {…`).
____________
¹ or any other capital letter of your choice :wink: @fengdaolong

**Comment by Logan007** [comment]
> Ok, so we should add a specific field to n2n_sn_t structure (e.g., char federation[N2N_FEDERATION_SIZE]) to store the federation name.

Maybe one field more… How do the supernodes remain distinguishable in the community and can be found in the community list by some information which only is carried in the packets?

**Comment by fcarli3** [comment]
> Maybe one field more… How do the supernodes remain distinguishable in the community and can be found in the community list by some information which only is carried in the packets?

We could add a field and using it as key ... A MAC address could work, but how can we know a MAC address of a supernode?

> char federation[N2N_FEDERATION_SIZE] field content could be converted to that special community, maybe by calling a new function like int add_federation (n2n_sn_t *sss, char * federation, …) or so

Yes, in this function `add_federation()` I could create a new `sn_community` structure that represents our federation and I could add it to the community list, as the federation is a (special) community

**Comment by Logan007** [comment]
> A MAC address could work

MAC is a good idea.

> how can we know a MAC address of a supernode

Just copy the edge way of doing it: Another command line option or randomly generate it if not given through command line.
