### ISSUE TITLE
Purge-and-re-registration process for supernodes

### ISSUE THREAD

**Issue by fcarli3** [ntop/n2n#436]
This process iterates through all the communities to find the federation. The regular community purge could be used for this as it regularly walks through the communities, it will also find the federation. We need to add `if(comm.is_federation) iterate through all supernodes and send REGISTER_SUPER` to the existing code

**Comment by Logan007** [comment]
A ~~short~~ thought on purging and re-registration:

The list of new supernodes that arrives as "payload" of the REGISTER_SUPER_ACK should not directly be "trusted" to be valid. We should only do so if we have sent an own REGISTER_SUPER and received a proper REGISTER_SUPER_ACK.

Why? Because a supernode listed in REGISTER_SUPER_ACK could have gone in the meanwhile. And if we trust it and even forward it to other supernodes (in other REGISTER_SUPER_ACKs), this might remain a ping-ponged "zombie" in some lists.

So, the purging strategy should consider the following points (parts of it might already be in the code):

- A re-registration interval after which we re-register with the other supernodes. Why not use the same time-out which is used by the edges (20 seconds, helps to keep ports open)? Whenever an answer arrives (REGISTER_SUPER_ACK) or a new registration request (REGISTER_SUPER from another supernode) the timestamp `last_seen` needs to be updated.¹

- Only forward _current_ (that are proven to be alive) supernodes (with `last_seen < 20 seconds`) along with a REGISTER_SUPER_ACK.

- A time-out interval after which a supernode gets purged if not seen, maybe 90 seconds (same as for nodes, I do no remember too well, have not looked at that part of the code for long).

But then, the question is, what timestamp `last_seen` do the freshly received supernodes from the REGISTER_SUPER_ACK payload should get in this list? **Either** a special one (NULL?) to indicate that this is still one to test (but then: for how long can it stay in this list, how can we know how long it has been in this list?) **or** (probably better) any reasonable value (depending on your purge strategy) between 21 (so, it is not considered _current_ anymore) and 69 seconds ago (so it does not get purged immediately but will get a chance to be (re-)tried in the auto-re-registration.

That way, you would have three classes of supernodes (just by the timestamp):

- `last_seen < 20` :: current
- `20 < last_seen < 90` :: status unsure, retry
- `90 < last_seen` :: too old, purge

Well, to be specific, it should read `now - last_seen`…

_____________
_even more edited for clarification_

¹ not so sure if also PACKETs or broadcasts to forward can trigger a timestamp update; **maybe not** for every packet that has the `from_supernode` flag set the forwarding supernode can be  identified easily… think about it later

**Comment by fcarli3** [comment]
Ok, so we should add a `case` in `process_udp` to handle a REGISTER_SUPER_ACK message. In this `case`, we could decode the received packet and call the specific function to check the list of supernodes. Is it better to write a new function for re-registration and purge? Can we use the existing purge function with some changes? What do you think?

**Comment by Logan007** [comment]
The switch-cases  (or just some `if`s, depending on how it fits into that part of the code) would be required in the regularly called function, that checks for purgable communities, **not** in the REGISTER_SUPER_ACK handling.

I do not think that the purging needs a complete re-write. Some changes for federation-community handling will be required. The time-stamps handling might be one of them. If I am not mistaken, the purging should go through all communities, so, you could just handle the federation-related specialties with an `if (...is_federation)` there.

The handling of arriving REGISTER_SUPER_ACKs is basically to
- check/decode the required fields, if any (always check `from_supernode == comm.is_federation`)
- reset the timestamp of the sending supernode in the local federation list
- call the `add_supernodes_to_federation_from_reg_super_ack_payload(…)` (you might find a shorter name). This routine just needs to go through the payload, omit the ones already known, and add the others with a _special_ (see above) timestamp, e.g. 50 seconds old (`now - 50`) or maybe more generic: half of the difference between the adjustable 20 seconds and 90 seconds limit. While creating this function you might find that maybe the socket is not enough to send in the REGISTER_SUPER_ACK payload (sorry, I did not realize until now that the MAC was mentioned in the other discussion), but _maybe_ the MAC would make a good addition.
- The decision on how each supernode in the federation list gets treated (keep, re-register, purge) is not to be made here, but in the purge-function (see above). Here, it is just the new nodes we add and the time stamp we put.

The edge's way of handling REGISTER_SUPER_ACKs might be worth having a look at.

**Comment by fcarli3** [comment]
> call the add_supernodes_to_federation_from_reg_super_ack_payload(…) (you might find a shorter name). This routine just needs to go through the payload, omit the ones already known, and add the others with a special (see above) timestamp, e.g. 50 seconds old (now - 50) or maybe more generic: half of the difference between the adjustable 20 seconds and 90 seconds limit


I've tried to write this function but I'm not sure if it could be work because maybe I didn't understand very well how iterate through `REGISTER_SUPER_ACK` payload. The code is the following (just to show my idea): 

```C
/** Iterate through REGISTER_SUPER_ACK payload and add new supernodes with a legal timetsamp 
 *  (half of the difference between the adjustable 20 seconds and 90 seconds limit) to the federation list
 */
static int add_sn_to_federation_from_register_super_ack(n2n_sn_t *sss, n2n_REGISTER_SUPER_ACK_t ack){
	struct sn_community *fed;
	struct peer_info *peer, *tmp, *sn;

	HASH_FIND_COMMUNITY(sss->communities, sss->federation, fed);

	if(fed != NULL){
		HASH_ITER(hh, fed->edges, peer, tmp){
			HASH_FIND_PEER(fed->edges, ack.mac_addr, sn);
			if(sn == NULL){
				sn = (struct peer_info*)calloc(1,sizeof(struct peer_info));
				memcpy(sn->mac_addr,ack->mac_addr,sizeof(n2n_mac_t));
				memcpy(sn->dev_addr,ack->dev_addr,sizeof(n2n_ip_subnet_t));
				memcpy(sn->sock,ack->sn_bak,sizeof(n2n_sock_t));
				sn->last_seen = TEST_TIME; 
				HASH_ADD_PEER(fed->edges, sn);
			}
		}
	}

	return 0; /* OK */

}
```

**Comment by Logan007** [comment]
Your idea is that the loop shall iterate through the already known edges (fed->edges) and adds those from the packet, that are not found in the community yet, right? That is fine. Another way to do it would be to iterate through the packet and and check for each entry, if it already is in our federation community.

Talking about "iteration through the packet", I see that your "HASH_FIND_PEER" always uses `ack.mac_addr` to find a peer and always looks in `fed-> edges`. So, if you ITERate through the federation community, the HASH_FIND should search the packet. Or, if you decide to do it the other way 'round¹, you need to iterate through the packet, namely the additional payload. As we know how many entries are sent (`sn_num`), a simple `for(…)` would do. Then, you can easily use HASH_FIND to search for the entry in the federation.

_____________
¹ which would be easier, I guess, because iteration along packet together with HASH_FIND on federation could be easier iterating the community and having no HASH_FIND on the packet

**Comment by fcarli3** [comment]
> Or, if you decide to do it the other way 'round¹, you need to iterate through the packet, namely the additional payload. As we know how many entries are sent (sn_num), a simple for(…) would do. Then, you can easily use HASH_FIND to search for the entry in the federation

Yes, this strategy seems better than the other one. But I have another doubt about iteration through the payload of the packet. In fact REGISTER_SUPER_ACK packet isn't an array, and I can't check `ack[i].mac_addr`. So how can I check the n-th entry in the payload?
I've modified the code like this but I don't know if `for(..)` iterates correctly through the entries in the payload.

```C
if(fed != NULL){
	for(i=0; i<ack.num_sn; i++){
		HASH_FIND_PEER(fed->edges, ack.mac_addr, peer);
		if(peer == NULL){
			peer = (struct peer_info *)calloc(1,sizeof(struct peer_info));
			memcpy(&(peer->mac_addr), ack.mac_addr, sizeof(n2n_mac_t));
			memcpy(&(peer->dev_addr),ack.dev_addr,sizeof(n2n_ip_subnet_t));
			memcpy(&(peer->sock),ack.sn_bak,sizeof(n2n_sock_t));
			peer->last_seen = TEST_TIME;
			HASH_ADD_PEER(fed->edges, peer);
		}
	}
}
```

**Comment by Logan007** [comment]
`for` looks good.

The only advice I can give here relies on data structure sizes:

- use a pointer to the (first) MAC data (right after `sn_num`? or is the socket first? can't remember), should be determined outside the loop, as pointer type, either pointer to anything (`*void`) or maybe (better) pointer to `mac_addr_t`.
- use this pointer (or its dereference if required) to HASH_FIND the node with the MAC to which the pointer is pointing inside the federation community, if present
- the data follows byte after byte in memory, so just increase the pointer by the whole data structure size (MAC + socket size) at the end of the loop or somewhere else after the HASH_FIND (but outside the `if` block if I am not mistaken).

**Comment by fcarli3** [comment]
In the purge function I've added `if(comm.is_federation) re_register_and_purge() ...`. In this new function I iterate through the federation and  check `now - last_seen` value. So I obtain 3 different cases:

- `now - last_seen < 20`: `continue`, current supernode
- `20 < now - last_seen < 90`: ensure status, re-register 
-  `now - last_seen > 90`: too old, purge

In the third case I remove the supernode from the federation and free the memory. 
In the second case my idea is to send a REGISTER_SUPER message to register again at the original supernode. Could I use the existing code in `src/edge_utils.c` and create a special function (with some adjustments of course) to send REGISTER_SUPER ?

**Comment by Logan007** [comment]
Having a quick look at `send_register_super()` in the `edge_utils.c` file (line 749), I do not see any reason not to use it.

The already present `purge_expired_registrations()` (see `n2n.c`) will help to do the purge. It uses the `PURGE_REGISTRATION_FREQUENCY` macro which seems to be far below the limit of 90 seconds. Is it 30? We could go with that, too (instead of 90). **But**, this is just 10 seconds more than the other 20 second-limit. And unfortunately, the socket timeout `SOCKET_TIMEOUT_INTERVAL_SECS` is set to 10 seconds (used in edge, not in supernode yet where it gets set directly using literally `10`, we could fix that along the way) which means that (if no other packet arrives in between), the main loop runs again after 10 seconds… which in turn allows maybe for only one REGISTER_SUPER to be sent out. We might also need to re-think all these limits a little bit.

**Comment by Logan007** [comment]
_P. S._ If we want to stick with `90` but do not want to duplicate too much of the code, we could just make the timeout an additional paramter to the `purge_expired_registrations()` function and either pass `PURGE_REGISTRATION_FREQUENCY` or `PURGE_FEDERATION_NODE_INTERVAL` (tbd).

**Comment by fcarli3** [comment]
Sorry but I didn't understand very well how I should use the limit of 90 seconds in `purge_expired_registrations()`. I saw this function in `src/n2n.c` and, as you said, it uses `PURGE_REGISTRATIONS_FREQUENCY` macro. I thought to define a new macro (`PURGE_FEDERATION_NODE_INTERVAL` as you suggested) and use it to check `now - last_seen`, but how should I use in `purge_expired_registrations()`?

Moreover, I added a specific `case` to handle a REGISTER_SUPER_ACK packet in `process_udp`. Seeing how an edge manages REGISTER_SUPER_ACK (file `src/edge_utils.c`), how could I check the cookie here? Beacuse a supernode doesn't have a field `last_cookie` to compare with cookie of REGISTER_SUPER_ACK.

**Comment by Logan007** [comment]
> I thought to define a new macro `PURGE_FEDERATION_NODE_INTERVAL`

:+1:

> but how should I use in `purge_expired_registrations()`

What about a new parameter to that function, namely the `timeout` to be used? When the function gets called, you can either pass `PURGE_REGISTRATIONS_FREQUENCY` (the already existent calls) or `PURGE_FEDERATION_NODE_INTERVAL` (the new calls). That way, we can re-use the code because it basically does the same in both cases – only with a different timeout.

> how could I check the cookie here?

Two options: either ignore the returned cookie  at the supernode **or** add the `last_cookie` to the `peer_info` structure. That could also be used in the edges to store the cookies from REGISTER and REGISTER_ACK – I only sparsely remember how cookies are treated between edge nodes; I only remember cookies stored for supernodes somewhere in `eee`.

Maybe, some day, when the edges might store the available supernodes also as _list of nodes_ relying on  `peer_info`, the cookie field would be helpful to have – it seems to be the more general approach.
