### ISSUE TITLE
Which supernodes intialize the federation list

### ISSUE THREAD

**Issue by fcarli3** [ntop/n2n#451]
We could initialize the federation list using a parameter like edge's `-l` that adds several supernodes to the edge if given several times.  As the supernode has already `-l` parameter, we might use another letter (e.g. change the supernode's current `-l` in  `-p` to match the edge's port parameter `-p`).

Additionally, we would need to mark the supernodes given by command line as "unpurgeable", they may never be purged as they are considered anchors. The peer_info needs a corresponding flag (e.g. `is_purgeable` like the field of a community) and the purge logic needs a slight update towards this idea: "Never purge those nodes even if older than the limit and always retry those for re-registration, no matter how old they are"

**Comment by fcarli3** [comment]
@Logan007  I've thought about how implement the function that adds the supernode to the federation list. How could we convert a supernode's name ? Because my idea is to do a function that takes the string, splits it in 'supernode' and 'port' and then fulfills a new `peer_info` structure for the provided supernode. That way, we will need to know at least `mac_addr`, `dev_addr` and `sock`

**Comment by Logan007** [comment]
I guess the edge's current `-l` should already do it for `-l <ip:port>`.

But you have just made a great point here: How to add the MAC address to the peer_list (at the edge) if we only pass IP and port?!

We probably need to leave the MAC for the anchor supernodes (those passed through `-l`) reset (zero MAC) and treat them in a special way (they also wear that "unpurgeable flag" which could be considered synonym here for anchor – or shall we use a zero MAC for that purpose?).

Inserting freshly received supernodes from REGISTER_SUPER_ACK needs special handling then because supernodes in the list could have zero-MAC. How to solve this? In case of zero-MACs present, we might need to compare the socket as well and replace the zero-MACs as soon as we receive their data.

Or: We accept that we might have anchor supernodes twice in our list: One with zero MAC (from command line) and another one with real MAC (received later from REGISTER_SUPER_ACK from other supernodes).

However, we could try to make sure to remove doublets by **either** checking for same sockets from time to time (not sure how reliable sockets especially ports are) **(and) or** by replacing the zero-MACs with real MACs as soon as we happen to register with one of the anchor nodes (those are the only one known in the beginning) and then remove doublets if any. How will we know which zero-MAC an answering supernode (and its MAC in the response) could fill?  Again, either by evaluating socket data or by using cookies as temporal identifiers! Every REGISTER_SUPER should have its own distinct random cookie which gets returned with the ACK. Also, the edge should store the `last_cookie` for each supernode (it does it already, we would need to transfer this into the peer_info structure anyway), so we can find out.

So, there are options. I can't see yet which one would be easier to implement. Perhaps you know better about sockets and their use for comparison. Or do you want to go down cookie road?  The alternatives above add complexity. Maybe there are some simpler ways to go and we just have not found them yet.

**Comment by fcarli3** [comment]
> Inserting freshly received supernodes from REGISTER_SUPER_ACK needs special handling then because supernodes in the list could have zero-MAC. How to solve this? In case of zero-MACs present, we might need to compare the socket as well and replace the zero-MACs as soon as we receive their data.

This option seems easier then others, but I don't know much about comparison between socket. Moreover, how could we know socket from `-l <supernode:port>`?

**Comment by Logan007** [comment]
> comparison between socket

If it is just the pure data structure, you could either use `memcmp` or a field-wise comparison would do. Use `memcmp` only if we can be sure that the unused IP address (IPv4 or IPv6) is zeroed.

> how could we know socket from -l <supernode:port>?

According to `n2n_sock_t`'s data structure, it does not contain much apart from port and IP address.

**Comment by fcarli3** [comment]
So if we go this way, we could reset MAC in the anchor supernodes passed by parameter and treat in a special way. Then, when we have to iterate through the federation list, first we could search using MAC and if we won't find anything then we'll search by socket. Right?

**Comment by Logan007** [comment]
Yes. Good thing here is that in the second run we could skip the ones not having zero-MAC.

I just wonder how we can replace the zero-MAC with the real one if we completely stop the search which is successful in the first round (by MAC). Maybe, we should do the second search (by socket) anyway, even if the first was successful. If we count the supernodes with zero-MAC and keep track of them, we can skip the second search if this number has reached 0.

Not sure yet if there is a more optimal way to do it.

**Comment by fcarli3** [comment]
>  If we count the supernodes with zero-MAC and keep track of them, we can skip the second search if this number has reached 0

How do you suggest to do that? 
If I'm not wrong, you said we should modify `add_sn_to_federation_from_register_super_ack()` function where we add freshly received supernodes. My idea is to check if MAC is not zero and then iterate through the payload of the message. If MAC is zero, we could count how many zero-MAC there are and run the second loop, where we use socket to search.

> Not sure yet if there is a more optimal way to do it

At the moment I have no better solution in mind ...

**Comment by Logan007** [comment]
> If I'm not wrong, you said we should modify add_sn_to_federation_from_register_super_ack() function where we add freshly received supernodes. 

Right.

> My idea is to check if MAC is not zero and then iterate through the payload of the message. 

Maybe the other way 'round, i.e. iterating through the payload and checking for zero MAC? Looking for a matching MAC might be easier in the hash list.

> If MAC is zero, we could count how many zero-MAC there are and run the second loop, where we use socket to search.

Umm, maybe we could do it in one loop then. While iterating through the payload, based on zero or non-zero-MAC, decide **if** to do hash list lookup by MAC or search by socket.

**Comment by fcarli3** [comment]
Your idea is to do a search like the following if I've understand well 

```C
if(fed != NULL){
    tmp_sock = &(ack.sn_bak);
    tmp_mac = &(ack.mac_addr);
    for(i=0; i<ack.num_sn; i++){

      if(tmp_mac != ZERO_MAC) HASH_FIND_PEER(fed->edges, &tmp_mac, peer);
      else HASH_FIND_PEER(fed->edges, &tmp_sock, peer);

      if(peer == NULL){
        peer = (struct peer_info *)calloc(1,sizeof(struct peer_info));
	memcpy(&(peer->sock),tmp_sock,sizeof(n2n_sock_t));
	if(tmp_mac != ZERO_MAC) memcpy(&(peer->mac_addr), &tmp_mac, sizeof(n2n_mac_t));
        else num_zero_mac++;
	peer->dev_addr.net_addr = ntohs(ack.dev_addr.net_addr);
	peer->dev_addr.net_bitlen = mask2bitlen(ntohl(ack.dev_addr.net_bitlen));
	peer->last_seen = TEST_TIME;
	HASH_ADD_PEER(fed->edges, peer);
      }
      tmp_sock += sizeof(n2n_mac_t);
      tmp_mac += sizeof(n2n_sock_t);
    }
  }
```

**Comment by Logan007** [comment]
Roughly speaking, that was my idea. But I guess I missed one point. Your idea was much better. At least, if we do not allow zero-MACs in REGISTER_SUPER_ACK payload (but we might want to). So, outer iteration should go through our internal list (because that is where we could encounter zero-MACs, so we can do the `if` on it and search the payload either by MAC or socket.

By the way, HASH_FIND_PEER  will only work with MAC as they are the _key_. But it seems that [multiple keys](https://troydhanson.github.io/uthash/userguide.html#_items_with_multiple_keys) are supported. Just an idea…

Your code above reminds me that the sender's MAC (from ack.-structure) should be used to find (by socket) to eventually fill up the missing MAC (first time registration to an otherwise unknown anchor node).

**Comment by Logan007** [comment]
It is getting very interesting now: Same data structure with two keys of which one might be missing. Avoid doublets!

**Comment by fcarli3** [comment]
> But it seems that multiple keys are supported. Just an idea…

I read the link and if I'm not wrong we can use two different keys but with two distinct hash tables, so we could add a new field (e.g. `struct peer_info *edge_by_socks`) represents an hash table to `sn_community` structure

**Comment by Logan007** [comment]
In my opinion, two structures would be okay even though it adds complexity to the code by handling two data-structures.

Another alternative would be to manually handle it, i.e. by adding an HASH-FIND-equivalent which searches by socket and/or MAC instead, and then encapsulate it in an own set of functions, e.g. `find_node_by_mac_or_socket_and remove_duplicates_if_any (output_pointer_to_sn_node, input_pointer_to_node, input_pointer_to_hash_list)` and/or a corresponding `add_node_by_mac_or_socket_and remove_duplicates_if_any (output_pointer_to_sn_node, input_pointer_to_node, input_pointer_to_hash_list)` working on one list only (so we do not have to adopt the data structure) and handling it all (the different cases of zero MAC…, as discussed above).

Once that is implemented correctly, you do not have to worry anymore and just need to call it when handling REGISTER_SUPER_ACK payload.
