### ISSUE TITLE
compiling 2.8 source on RaspberryPi 3 -->  CFLAGS="-03 -march=native" errors out

### ISSUE THREAD

**Issue by frenchfaso** [ntop/n2n#457]
Just downloaded the source code and tried compiling with the optimizations as suggested in the compilation readme:
> ./configure CFLAGS="-O3 -march=native"

it errors out with the following:

> configure: error: unrecognized option: '-march=native'

the ./configure without flags works though (but then, edge -A3 does not work :-( )

**Comment by Logan007** [comment]
| ./configure CFLAGS="-O3 -march=native"

Is `gcc` your C compiler?

> but then, edge -A3 does not work :-( )

AES was included in the edge and thus `-A3` should independently be available from compilation flags. What is the exact error you see using `-A3`?

**Comment by frenchfaso** [comment]
> Is gcc your C compiler?

Should be.. I' ve installed the package "build-essentials"  on Raspbian, and gcc is definitly there:

> pi@raspberrypi:~ $ gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

starting edge with the -A3 gives me this error:

> 07/Oct/2020 16:12:08 [edge_utils.c:2575] Adding supernode[0] = supernode.ntop.org:7777
07/Oct/2020 16:12:08 [edge.c:268] the AES-CBC cipher given by -A_ option is not supported in this version.

Source downloaded from the releases page.

**Comment by Logan007** [comment]
> Should be.. I' ve installed the package "build-essentials" on Raspbian, and gcc is definitly there:

Not sure what happens to `-march=native`. I realized you were talking about 2.8 in which you need to manually add it to the Makefile if I remember correctly. You could try. I think there was a line with `OPTFLAGS` flags or so. You could give it a try and add it there. It will not give you AES though.

> starting edge with the -A3 gives me this error:

Oh, I mistakenly thought you were talking about current dev… I think AES was made a permanent addition in 2.9, not in 2.8 yet.  So, you are right. You could however add it (automatically) by installing openSSL which will be detected at compile time.

**Comment by frenchfaso** [comment]
> Not sure what happens to `-march=native`

well... that's embarrassing... turns out while doing it from Ubuntu through vnc --> OSX terminal the ' " ' was some weird unicode character I suppose, so the 

> CFLAGS="-O3 -march=native"

was erroring out. It works fine now.
I have one last issue, what package is supposed to be installed to enable AES with this configure command:

> ./configure --with-openssl CFLAGS="-O3 -march=native"

I've installed (I think at least..) OpenSSL with "sudo apt install openssl" but the configure step finishes with:

> configure: WARNING: unrecognized options: --with-openssl

**Comment by frenchfaso** [comment]
Nevermind, I figured it out!

> sudo apt install libssl-dev

seems like the "--with-openssl" is not necessary, right?
Thanks for all the help!

**Comment by Logan007** [comment]
> what package is supposed to be installed to enable AES with this configure command:
> ./configure --with-openssl CFLAGS="-O3 -march=native"

If you compile **2.8**,  openSSL will be recognized automatically during configuration (please `make clean` again). Both, openSSL 1.0 or 1.1 should work but for AES, I would recommend openSSL 1.1 (for speed). So, yes: no parameter required.

Starting from current _dev_ **2.9**, we replaced the auto-detection because we got independent from openSSL, all ciphers are integrated in n2n and will be used by default. The  `--with-openssl` configuration parameter was introduced to override this default and fulfill users' needs in case they prefer openSSL.

**Comment by frenchfaso** [comment]
> The `--with-openssl` configuration parameter was introduced to override this default and fulfill users' needs in case they prefer openSSL.

There we go! Now I get it :-)
thanks again for all the help!

**Comment by Logan007** [comment]
You are very welcome!

If you still read this: I would be interested in the output of the `tools/n2n-benchmark` utility on your Raspberry.

**Comment by frenchfaso** [comment]
Hy @Logan007 sorry for the long delay,
on a fresh install of RaspberryPi OS Desktop (Raspberry Pi 3 Model B Rev 1.2)
I had to install 2 packages to compile n2n:

> sudo apt install automake libssl-dev

Here are 3 runs with 

> ./configure

![2020-10-08-192407_1280x720_scrot](https://user-images.githubusercontent.com/1913203/95502257-d99cff80-09a9-11eb-9482-95bccb3eb446.png)

and here with 

> ./configure CFLAGS="-O3 -march=native"

![2020-10-08-192724_1280x720_scrot](https://user-images.githubusercontent.com/1913203/95502445-241e7c00-09aa-11eb-9231-e68b4f6944a2.png)

**Comment by Logan007** [comment]
Thank you so much!

I wanted to compare it to what I get on my Raspberry 3B+ (don't know about revision, no overclocking, no specially compiled libs) running on **32**-bit Arch using **2.9**'s **internal** ciphers (`CFLAGS=""` – otherwise you get residual CFLAGS from system-wide setting or former compiles, I assume `-O2` in your case) and would like to share the results (the output format of benchmark tool has changed a bit; also, I included the `-d` output):

![n2nRPi32x](https://user-images.githubusercontent.com/46396513/95543378-169fdb00-0a18-11eb-83c4-6e2a1ab38231.gif)

The following is after compiling configuring `CFLAGS="-O3 -march=native"`:

![n2nRPi32O3n](https://user-images.githubusercontent.com/46396513/95545684-51a50d00-0a1e-11eb-8e30-fcd887663756.gif)

The following shows the results if **openSSL** 1.1 is included (only AES and especially ChaCha20 benefit; `CFLAGS="-O3 -march=native" --with-openssl` )

![n2nRPi32O3nS](https://user-images.githubusercontent.com/46396513/95545709-5ec1fc00-0a1e-11eb-915a-94df263bb578.gif)

**1st CONCLUSION** Even though the internal ciphers have seen some acceleration compared to **2.8** even on Raspberry Pi, I might have a look into how to make more and better use of ARM NEON for internal ciphers…

Ciphers seem to benefit from **64**-bit Arch (`CFLAGS="-O3 -march=native`):

![n2nRPi64O3n](https://user-images.githubusercontent.com/46396513/95548606-2b36a000-0a25-11eb-8502-1946e4aa3092.gif)

Interesting finding here: If compiled with openSSL support, AES falls behind n2n's internal version while ChaCha20 still benefits:

![n2nRPi64O3nS](https://user-images.githubusercontent.com/46396513/95548328-83b96d80-0a24-11eb-90ce-a91cef499b4b.gif)

Even more interesting: If I manually disable SPECK's internal NEON support, it runs much faster:

![n2nRPi64O3nxN](https://user-images.githubusercontent.com/46396513/95549000-ff67ea00-0a25-11eb-8541-9da258f8ed36.gif)

**2nd CONCLUSION** I will review SPECK's NEON implementation and maybe disable it.

**Comment by frenchfaso** [comment]
@Logan007 Looking forward to the "zero-dependencies" (almost?) version!
Great to see the compression algos added to the benchmark.

Ouch! I wasn't aware of the residual CFLAGS problem and the -d option :-P
Here are the updated runs:

> ./configure CFLAGS=""

![2020-10-10-114652_1280x720_scrot](https://user-images.githubusercontent.com/1913203/95652160-71583600-0aef-11eb-8587-6d15398f00aa.png)

> ./configure CFLAGS="-O3 -march=native"

![2020-10-10-114917_1280x720_scrot](https://user-images.githubusercontent.com/1913203/95652163-774e1700-0aef-11eb-9053-ccfc9457022a.png)

**Comment by Logan007** [comment]
Thank you for the update!

> Looking forward to the "zero-dependencies" (almost?) version!

Stay tuned!

Current `dev` already is stand-alone if you can refrain from optional zstd compression. From what I have seen source code-wise, it seems a bit bulky to include.

Also, openSSL probably will remain an additional user-specified option for platforms that can afford the additional space and on which openSSL might perform better than bare n2n (default).
