### ISSUE TITLE
 Increase bandwidth

### ISSUE THREAD

**Issue by zjbdiy** [ntop/n2n#534]
Sorry, I can't speak English, please forgive me for using translation

I have two windows and two edges running
a->%~dp0edge.exe -c Wzyd254 -a 172.10.10.3 -l serverip:5566 -r -M 1500 -D
b->%~dp0edge.exe -c Wzyd254 -a 172.10.10.2 -l serverip:5566 -r -M 1500 -D

I tried to test the bandwidth with iperf3 using a as the server and B as the client
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  11.6 MBytes  9.75 Mbits/sec                  sender
[  4]   0.00-10.00  sec  11.5 MBytes  9.66 Mbits/sec                  receiver

Then I use the kcptun proxy
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  34.5 MBytes  28.9 Mbits/sec                  sender
[  4]   0.00-10.00  sec  30.1 MBytes  25.2 Mbits/sec                  receiver

I think n2n is nearly perfect for me. Is there any good way to improve bandwidth?

Windows sharing can't change the port, so I can't use proxy mode

Thank you very much.

**Comment by Logan007** [comment]
Does Windows' Visual Studio support compiler optimizations like `-O3` option? That might already give you a significant overall speed-up.

You seemingly do not use encryption. If you use encryption, you can try to enable Intel specific code paths. Have you seen our [Building](https://github.com/ntop/n2n/blob/dev/doc/Building.md) document? I am not sure how the `-march=native` compiler option translates from `gcc` to Windows' Visual Studio, but it would speed up encryption by a lot – again, if encryption were the bottleneck.

**Comment by zjbdiy** [comment]
I use lucktu compiled 2.7, I don't know which compilation options are used, I will try to compile next

Thanks again

**Comment by zjbdiy** [comment]
I've tried to compile
However, the file in the compiled document does not exist

/*
md build
cd build
cmake ..

MSBuild edge.vcxproj /t:Build /p:Configuration=Release
MSBuild supernode.vcxproj /t:Build /p:Configuration=Release
*/

I have no experience in compiling
Please help me if I need to use other tools, other instructions?

**Comment by Logan007** [comment]
The instruction for compilation are somewhat older, but should basically still be working. The only thing I heard about is that it requires a manual `config.h` file (see #366).

I use Linux only but I know that some people successfully compile on Windows. I hope they show up in this discussion and could give further advice.

**Comment by zjbdiy** [comment]
If my question bothers you, I'm sorry, I will stop

After learning, I have successfully compiled the Windows version
The speed of 2.9 is significantly higher than that of 2.7
But the - 03 speed did not improve

The supernode l parameter seems to have been changed to P, port

I found a bug that prompts me when my view restarts edge
15/Dec/2020 19:03:08 [edge_utils.c:2187] ERROR: 00:FF:E4:5B:15:28 is already used. Stopping the program.
This bug seems to be related to supernode. You can start edge again after restarting supernode

**Comment by Logan007** [comment]
> If my question bothers you, I'm sorry, I will stop

Please do **not** stop! Feedback is essential for development and I love to give users a hand. How else could we receive feedback if we did differently? From my point of view, every discussion keeps this self-amplifying circle running!

> But the - 03 speed did not improve

Oh, too bad. Googling "visual studio compiler optimization" I find that it might be `/O2` (or `/Ox`) instead of `-O3` but I am not all too deep into Windows.

> The supernode l parameter seems to have been changed to P, port

Yes. Actually, 2.9 is not a real version – we probably will never see a 2.9 stable release (last stable was 2.8). 2.9 is just an alias for _current dev_ which in this case prepares the somewhen upcoming 3.0. And, as 3.0 is a major version number change, we performed some changes that break compatibility to the regular 2.x versions. That could be about network packet format but also command line options. Here, supernode's `-l` has been changed to `-p` in order to make it more comparable to edge syntax.

> I found a bug that prompts me when my view restarts edge
15/Dec/2020 19:03:08 [edge_utils.c:2187] ERROR: 00:FF:E4:5B:15:28 is already used. Stopping the program.

This is supposed to be a feature and not a bug… :wink: It shall prevent MAC spoofing and should not be a problem at all if the edge terminated normally (and internally is able to send a de-register message to the supernode before the program really exits). Otherwise, your edge will have to wait a while before it can be re-connect or it needs another MAC and IP address.

How did you stop the edge?

> After learning, I have successfully compiled the Windows version

I am glad that it worked out for you! From your experience, is there anything missing in our compilation guide?

**Comment by zjbdiy** [comment]
Thank you for your reply. About ending edge, the situation is the same as you described

Before I killed the process directly, I tried to close the script, can connect again, can work

There is no problem compiling the script. The previous problem was that the setting of the environment variable caused the cmake error

I will learn about windows compilation and continue testing

**Comment by Logan007** [comment]
Thank you for your feedback. Actually, the optimization options usually need to go into the compiler. I am not sure if the MSBuild.exe is the right place. Maybe somewhere in the CMake.list file (for the Windows build)?

If you find anything we should add to the Building document during your compilation experience, maybe a few extra bullet points, please feel free to tell us or to even create a pull request.

**Comment by Logan007** [comment]
Closed due to inactivity, considered solved. Please re-open if required.
