### ISSUE TITLE
Can one of supernode in federation stays behind NAT ?

### ISSUE THREAD

**Issue by timfaner** [ntop/n2n#567]
My network topology is like this :

<img width="601" alt="image" src="https://user-images.githubusercontent.com/15355789/103334676-3e4d8f00-4aad-11eb-8573-ebbd76e39fdd.png">

Some of edge nodes are behinds a __symmetrical__ NAT , and some are out of NAT scoop. Can I put a supernode behind NAT, to make edge nodes in NAT communicate without relay ?

**Comment by Logan007** [comment]
Well, it depends…

If the internal edges are on the same LAN, they might find each other via multicast without the help of a supernode. Note that this feature currently is not available in Windows version (see #65) of edges.

An internal supernode which can provide the internal IP addresses/sockets would help to connect the internal edges to each other.

In that given scenario, I think it could work only if the internal edges are not able to connect to the external supernode directly (because no ping, no registration then, only internal sockets distributed for p2p). Unfortunately we have no possibility for edges to prefer certain supernodes.

If the internal edges are non-Windows computers, or you  experimentally re-enable multicast (reportedly working for some on Windows), or following a solution @fengdaolong proposed in #65 (no idea yet if that could work), you do not need the internal supernode.

Please be aware that to work properly, the federation feature requires a fix which is not included in the _dev_ branch yet (see #568).

**Comment by fengdaolong** [comment]
> or following a solution @fengdaolong proposed in #65 (no idea yet if that could work),

This solution is feasible, and I have implemented the code. Although the multicast function can be used under windows, other error codes are occasionally prompted. I have not studied the reasons for these error codes. I can submit a PR in time for everyone to optimize it.

**Comment by timfaner** [comment]
Thanks for reply. Now I think maybe the best way to solve this problem is run Linux on every machine 😂

**Comment by Logan007** [comment]
This would be a general recommendation anyway… :wink:

**Comment by Logan007** [comment]
@timfaner, does #576 work for you on Windows?

**Comment by Logan007** [comment]
I assume #576 to be working on Windows. Please open a new issue if multicast peer detection causes problems.
