### ISSUE TITLE
Option to disable supernode tunneling completely?

### ISSUE THREAD

**Issue by HolgerHuo** [ntop/n2n#614]
Hi, I wonder if there is a way to completely disable the tunneling function of the supermodel when NAT connection is poor? My vps's bandwidth is limited and sometimes it was connected in the tunneling mode instead of p2p. Can I disable that using parameters or modifying the codes?

Btw, the doc's example used a wrong example
> -p=1234

The supernode's listening port should use -l parameter as it was described in the man page

> \-l <port>
> listen on the given UDP port

**Comment by Logan007** [comment]
> The supernode's listening port should use -l parameter as it was described in the man page

Up to version 2.8, the `-l` command-line option indeed is supposed to pass the UDP port.

Having an odd sub-version, 2.9 is not considered a _real_ version, there never will be a 2.9 stable release, it is just the current _dev_ for the next stable version. As that will be a major version release jumping to 3.0, we took the liberty to introduce some compatibility-breaking changes. That includes packet format as well as command-line parameters.

Starting from 2.9/3.0, the port will be passed by the `-p` parameter. That's what we already have changed in the 2.9/3.0 documentation (2.8 README still should and will show `-l`) and the help text.  By the way, the reason for this specific change is that we want to have supernode and edge parameters more in line as the new federation feature also allows to provide additional supernodes to the supernode's command-line.

You are right, `man` page still lacks revision and is a current [action item](https://github.com/ntop/n2n/issues/562) on our list.

>  completely disable the tunneling function of the supermodel ... Can I disable that using parameters ...

This has been suggested in #344; and #515 tried to solve it. We still are pondering this feature but it seems to require some more thoughts. Especially, it should extend the current `-S` option rather than creating yet another command-line option as outlined [here](https://github.com/ntop/n2n/pull/515#discussion_r534506507).

> ... or modifying the codes?

There probably is not just that one point in the code. Especially, as the PACKET messages through the supernode (those you want to avoid) also help the initial hole punching process (in addition to the REGISTER packets), things could become touchy. But if you want to give it a try, as a starting point, I would recommend the original [paper](http://luca.ntop.org/n2n.pdf) to get an impression of the underlying mechanism, read the [`/doc` folder](https://github.com/ntop/n2n/tree/dev/doc) documents, foremost the [Hacking](https://github.com/ntop/n2n/blob/dev/doc/Hacking.md) doc.

Please let us know what you find!

> when NAT connection is poor

If the regular STUN NAT hole punching does not work, you could try to use `-L <NAT level +-/1>` which is documented in more detail on the `man` page; that section is still valid. More information can be found in #115 – understanding those details is extremely advanced, from my point of view... :wink:

**Comment by HolgerHuo** [comment]
Thanks for your detailed explanation~

I *did* miss that issue when searching in the repository for I didn't find the appropriate word for *Forwarding*, sorry for the inconvenience.

#115 this really helped me for my NAT situation was the one of Symmetrical NAT using mobile network (LTE in specific). It seems to be the problem of mobile carriers and the port prediction mechanism looks really fascinating. I'll try them out now.

> But if you want to give it a try, as a starting point, I would recommend the original paper to get an impression of the underlying mechanism, read the /doc folder documents, foremost the Hacking doc.

I've tried hacking some codes this afternoon but I haven't had a solution yet. #515 is a brilliant idea but I wanted it to be filtered by the supernode only, without marking packets on the edge side, but it seems complicated ~~or to say, impossible~~ to handle that on the server side alone. I'll keep working on that.

Again, thanks for your great help and developing!

Stay safe.

**Comment by Logan007** [comment]
> I wanted it to be filtered by the supernode only, without marking packets on the edge side, but it seems complicated ~~or to say, impossible~~ to handle that on the server side alone

If a packet is sent out to the supernode, it already uses the bandwidth, even if the supernode ignores it. So, best thing would be to prevent PACKETs being sent out to the supernode if no p2p connection established. But then, the PACKETs role in the hole punching process kicks in.

Maybe, and this is just a thought, no idea if this is feasible, the edge could count PACKETs addressed to nodes in the `pending_peers` list (contains other edges with non-confirmed p2p status, they go the `known_peers` list as soon as confirmed) and only allow up to three or so. If there is no hole punching achieved until then, it doesn't seem too likely to happen anytime soon. So, if that `-S2` or whatever it will be called is configured, forwarding through the supernode could be omitted after these three PACKETs for that specific edge then. By the way, the forwarding decision is made in `find_peer_destination()`.

>  I'll keep working on that.

Again, let us know what you get. We are very open to pull community's contributions in!

**Comment by HolgerHuo** [comment]
Ok, thanks a lot!
