### ISSUE TITLE
Suggest simplifying the help message

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#654]
edge --help:
-S1 ... -S2 or -S
-S1 or -S do not connect p2p, always use the supernode
-S2 connects through TCP and only to the supernode

to

-S1 -S2 #Cancel the S
S1: not p2p, all communications go through supernode with UDP
S2: not p2p, all communications go through supernode with TCP

Continue to simplify parameter A? audacious, since it is no longer compatible with the previous V2. 
For example, -A1, ChaCha20, -A2, Twofish(cancel it? two or three types of encryption will do), -A3, Speck-CTR, default, aes, no, do not use with key

... ...

**Comment by Logan007** [comment]
@lucktu, thank you very much for the reminder. Indeed, we originally planned to deprecate the plain `-A`. I think we can do this. Especially as we announced `-A` as deprecated in the the version 2.8 help text when introducing the `-A_` syntax.

And of course, we can do this to `-S` as well.

One more change automatically comes with it: If we switch from "optional" to "mandatory" parameter option, the syntax will change from `-A3` to `-A 3` (note the whitespace between `A` and `3`), same for `S` then. For `-S`, it might look a bit strange on Windows because it does not support TCP (`-S 2`) yet. 

I know that some people would not like seeing command line syntax being jeopardized again. So, this requires discussion:

**Everybody**, are there any objections against adapting this part of command line syntax? Please share your thoughts!

Actually, I have been thinking about kicking a cipher, maybe even the slowest one. But then, on the other hand, we restrict user's choice: If we kicked Twofish, there only would be one block cipher (AES) left; ChaCha20 and SPECK are stream ciphers. I personally am very happy to use AES, especially as my platforms provide hardware acceleration, and I do not need Twofish at all. However, others do not have as much trust in NSA as I do and would prefer some independent block cipher, namely Bruce Schneier's Twofish. As [compiled here](https://github.com/ntop/n2n/blob/dev/doc/Crypto.md#overview), every cipher has its advantages and disadvantages.

So, my preference is to keep it in the code. Especially, as it should not eat too much binary space. But I am open to community's vote.

**Everybody**, what do you think about kicking a cipher? Or shall we even stick to only one? Maybe AES only?

**Comment by lucktu** [comment]
I think the default encryption should apply to any platform, if I had to choose, the first is aes, the second is chacha20.

**Comment by Logan007** [comment]
> default encryption ... the first is aes

I agree! I also think that AES is a reasonable choice for default, so we should keep it as default (automatically chosen if `-k` only).

> should apply to any platform

I do not see the platform as valid discriminator for cipher support. Some ciphers just run faster on some platforms than on others. It really depends on the scenario. In a mainly desktop environment with predominant AES hardware acceleration, I would tend to use AES. Others would use SPECK or ChaCha on non-accelerated platforms in case n2n is used a vpn-link between routers.

As of now, all ciphers are supported on each platform because they all are integrated in n2n's code. If we ever chose to kick some cipher, it is probably best to apply it to all platforms in the same way.

By the way, the **numbering scheme** that comes along with the `-A_` parameter does not indicate any preferences. The numbers are just easier to remember in the current way as [outlined before](https://github.com/ntop/n2n/issues/255#issuecomment-640414747).

Alternatively, concerning the **help text**, we could eradicate the hint to plain `-A` and leave the rest as it is.

**Comment by Logan007** [comment]
Okay, so I will just remove it from the help text but leave the solitary `-A` in the code. The next step would be to even delete it from the code, maybe in 3.2 then. I think that this is a good deprecation strategy (advertising the syntax as deprecated – do not advertise the syntax anymore but warn – do not accept anymore).

I will **not** switch to mandatory syntax (`-A 3`) but stick with the current optional one (`-A3`) while checking for a non-zero value provided (now causing fall-back to default and WARNING, later refusal). Same for `-z` and `-S` then.
