### ISSUE TITLE
If there is no supernode at startup, edge will exit

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#683]
When edge starts, if supernode is not valid, or the local computer is not networked, then edge will exit.

Hopefully you'll always be able to boot up edge and get back to work when the network is up and running.

Test: on n2n v.2.9.0.r873.c73e593

**Comment by Logan007** [comment]
>  if supernode is not valid, or the local computer is not networked, then edge will exit

Do you think we should change the default behavior? Should the edge should wait and retry until network is available? How can edge detect what the cause for "not reaching the supernode" is?

I have not seen that an arbitrary supernode IP address would lead to an immediate exit. What exactly did you specify?

> get back to work when the network is up and running

What if a wrong supernode was provided? Wouldn't it be better to quit edge immediately and notify the user instead of looping indefinitely waiting for the (invalid) supernode to become valid?

So, what shall we do? Please advise!

**Comment by lucktu** [comment]
On the remote computer (or a router with pppoe), I added "edge -c test -k best ...." to the boot, and when it started up, if there was no network, edge was lost until the next reboot.

V1 and v2 don't have this problem, v2.9 does. For v1 and v2, as long as the network is working, or supernode is working, then I can connect to it, very convenient.

**Comment by lucktu** [comment]
On the remote computer (or a router with pppoe), I added "edge -c test -k best ...." to the boot, and when it started up, if there was no network, edge was lost until the next reboot.

V1 and v2 don't have this problem, v2.9 does. For v1 and v2, as long as the network is working, or supernode is working, then I can connect to it, very convenient.

**Comment by Logan007** [comment]
I have just tried to disable all network but I still see the edge starting up, i.e. not exiting, and continuously throwing _"ERROR: sendto_fd sendto failed (101) Network is unreachable"_ until I restore network connections; it then immediately connects to the supernode.

I have not tried to run the `edge` at `runlevel 2` yet. Are you referring to this case? If so, a possible workaround could include to start the edge at `runlevel 3`.

**Comment by lucktu** [comment]
Actually, I'm running edge at runlevel 1

On my router, I ran these three edge and turned on ssh(admin/admin) so you could log in and test.
./edge3 -d TA -a 10.30.10.11 -c n2n -k test -l t1.lucktu.com:10090 &
./edge2 -d TB -a 10.20.10.11 -c n2n -k test -l t1.lucktu.com:10086 &
./edge1 -d TC -a 10.10.10.11 -c n2n -k test -l t1.lucktu.com:10082 -b &

edge1 --- edge_v1, edge2 --- edge_v2, edge3 --- edge_v2.9

When you test, please change the password. You can modify /etc/storage/started_script.sh, save (mtd_storage.sh save) and restart (reboot) it. put # before "ifconfig eth2.2 down" to see how edge is running. yu will see edge3 is different from the others.

At the same time, you can ping these ips: 10.10.10.10 / 10.20.10.10 / 10.30.10.10

**Comment by Logan007** [comment]
I have just tried to `ssh admin@10.30.10.11` using v3 (r911, current dev, as `-a 10.30.10.99`) without success (connection to your supernode working very well).  `ping 10.30.10.11` does not work either. I can `ping 10.30.10.10` though. Obviously, I will have to connect via v2 as v3 might not be running. Will try later.

`runlevel 1` is very early for a network application to start. Do you see a way to start it at `runlevel 3`?

**Comment by Logan007** [comment]
Got it and changed the pw. Will do some trials over the weekend. Thank you for this opportunity and especially your trust and confidence!

**Comment by Logan007** [comment]
Okay, I did some logging (`log3` along with the edges' executables) and found that name resolution is the issue.

I think we have changed the behavior to exit if an invalid `-l supernode-name:port` is provided. We found that it is better instead of re-trying an invalid supernode over and over again. 

In this case, if the network is still down, the initial name resolution returns an error and therefore the edge exits.

As a quick-fix, I replaced the name with the IP address in your script and `edge3` starts up very well.

I will see if we can distinguish different error codes, if they *are* different, in **initial** name resolution handling 

_EDIT_: Unfortunately, it turns out that it is the same error code `-2` in both cases, network down as well as gibberish or unknown name.

**Comment by lucktu** [comment]
In fact, I should say thank you, you are helping me, you make me better tomorrow! !

Thank you!

The machine is independent. Please feel free to use it.

**Comment by Logan007** [comment]
You are very welcome. I am just glad that this was not a too-hard-to-find bug.

So, shall we change to _"only warn and do no exit"_ if initial name resolution is not successful? I am not sure if we have changed some internal things related to supernode name resolution that would not allow this. I need to check.

~~_Actually, if I remember correctly, we introduced the current behavior along with the federation feature. We found it important that each supernode provided via command line must be valid, i.e. name resolves well, because we only want to announce valid supernodes into the whole federation. Allowing name resolution to fail would include a requirement to track supernode IP address validity at all places in the code._~~  [edge does not propagate any supernode information to federation, only supernodes do]

**Comment by lucktu** [comment]
Yeah, I think you found the problem. You're absolutely right.

In fact, my other process also failed, because that supernode(in it) isn't normally running, and only when I want it to work, I will start the supernode up and resume that process.

Waiting for your good news, thank you!

**Comment by Logan007** [comment]
I think #701 addresses this issue in a bearable way.
