### ISSUE TITLE
 Authentication error

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#691]
In TCP mode:

When I found my browser can not open a web page , I saw bellow info, seems something wrong , maybe there was a big firewall dropped my packages that destined  for supernode at that time. then I press CTRL + C to exit current connection.
```
03/May/2021 20:48:20 [edge_utils.c:1320] WARNING: Supernode not responding, now trying xx.xx.xx.xx:8080
03/May/2021 20:48:20 [edge_utils.c:208] Binding to local port 0
03/May/2021 20:48:20 [edge_utils.c:208] Binding to local port 0
03/May/2021 20:48:44 [edge_utils.c:1320] WARNING: Supernode not responding, now trying xx.xx.xx.xx:8080
03/May/2021 20:48:44 [edge_utils.c:208] Binding to local port 0
03/May/2021 20:48:44 [edge_utils.c:208] Binding to local port 0

```
Then I re-run my edge script , but it shows me bellow log ,   then I press CTRL + C to exit current connection again.

```
03/May/2021 20:50:20 [edge.c:1153] edge started
03/May/2021 20:50:20 [edge_utils.c:2434] ERROR: Authentication error. MAC or IP address already in use or not released yet by supernode.
Error: Nexthop has invalid gateway.
Failed to resolve interface "edge0": No such device
Failed to resolve interface "edge0": No such device
```
maybe just pass 2-4 minutes , I re-run my edge script ,then it worked again. so wired!  network issue ? how to optimize it ?

**Comment by Logan007** [comment]
`Failed to resolve interface "edge0": No such device` looks as if the device was gone in-between, something OS-specific, maybe updates? Does `ip link` show that `edge0` device?

**Comment by Logan007** [comment]
Current edge behavior has changed to not quit the edge in case of authentication error. It just might take a while (~90 sec) to connect if previous edge did not quit properly, but it does not quit during that time.

Other than that, `-M` disables spoofing protection at the supernode if required to get rid of authentication error.

**Comment by introspection3** [comment]
sir when we stop the edge process (we create it with child process),we send edgePs.kill('SIGINT') but it does no work.

**Comment by introspection3** [comment]
@Logan007 sir when we stop the edge process (we create it with child process),we send edgePs.kill('SIGINT') but it does no work.

 MAC or IP address already in use or not released yet by supernode

**Comment by Logan007** [comment]
> when we stop the edge process (we create it with child process),we send edgePs.kill('SIGINT') but it does no work.

I am not sure how you invoke it and how signaling in your environment works (please provide some more details), but usually, CTRL + C  ( == SIGINT) does work as well as `kill -SIGINT <pid>` does. It needs some time to finish, e.g. for sending out UNREGISTER_SUPER message  to supernode.

So, if you  do this at the end of some other parent process, you might want to wait a second or so before parent process hard-kills child process due to exit. Just guessing here as I am not aware of your setup.

> MAC or IP address already in use or not released yet by supernode

This is part of [spoofing protection](https://github.com/ntop/n2n/blob/c4d56574ef70392a25ac68e2c65d01879d31fafe/doc/Authentication.md#identity-based-scheme). Your edge may not have shut down properly, the UNREGISTER_SUPER did not arrive at the supernode. Therefore, the a new connection attempt is prevented for a while (90..120 sec or so). The newly spawned edge just needs to wait for that time.

So, you should make sure that the edge shuts down properly.

Alternatively, you can used `-M` at the supernode to disable spoofing checks – but this is less preferred.

**Comment by introspection3** [comment]
@Logan007 it does not work on windows,but it works on linux,same code

**Comment by Logan007** [comment]
I think we solved itz over at the other issue by pointing out that the Windows edge might need two  SIGINTs as well as by moving up the `send_unregister_super()`.

Shall we close this one?

**Comment by Logan007** [comment]
considered solved, please re-open if required
