### ISSUE TITLE
DDNS Bug

### ISSUE THREAD

**Issue by small-5** [ntop/n2n#703]
When edge uses DDNS to connect to the supernode and the IP changes,edge will always report error,but DDNS has been updated.Please Fix it,Thank you!
![1](https://user-images.githubusercontent.com/61473216/120928221-512c5580-c716-11eb-9d78-ef913da38905.png)

**Comment by Logan007** [comment]
What exact version do you use? This should have been fixed recently – two days ago.

**Comment by small-5** [comment]
I am using c55e3e32463d9821b7459c9c86108e6f364a1529. I just saw that 3c6ab56d3fdbc6464803cca61fe814f8b8fbbd6f has fixed this problem?

**Comment by Logan007** [comment]
Actually, `c55e3e3` should be working fine, but current _dev_ has honed it a bit more.

I have tested it with varying `/ectc/hosts` file entries, and the changes got accepted after a while...

**Comment by small-5** [comment]
Tomorrow I will update to the latest version to test it, thank you!
In addition,could you please add an option to supernode to turn off the function of mac authentication?Because in some cases, it is not necessary to start MAC anti spoofing.Thank you!

**Comment by Logan007** [comment]
> In addition,could you please add an option to supernode to turn off the function of mac authentication?Because in some cases, it is not necessary to start MAC anti spoofing.Thank you!

I will think about it... it actually should not be an issue if you softly kill your edge, please do not use `-9` on `kill`, just a simple `kill` or `killall`...

**Comment by small-5** [comment]
This problem occurs when I use reboot on ubuntu

**Comment by small-5** [comment]
I use 75ab1fc5aa2bf35f91f57241d650ab005e3a63b4 to compile and test. It will return to normal in about 3 to 4 minutes. I feel that the time is too long.
![无标题](https://user-images.githubusercontent.com/61473216/120943779-a2166b00-c763-11eb-9834-ab7e38f219ca.png)

**Comment by small-5** [comment]
Could you please change the logic? In the case of using domain name, if supernode does not respond, resolve the domain name first and then connect.

**Comment by Logan007** [comment]
> Could you please change the logic?

I have just put the DNS resolver into its own thread so it does not stall the complete edge which seems to have happened from time to time. So far, it follows a simple sleep–look-up–sleep-again cycle. You could adjust the sleep time `N2N_RESOLVE_INTERVAL` at `include/n2n_define.h:66`. It defaults to 300 seconds. In case of _name resolution error_ (not: the supernode-not-available case), it temporarily operates at a tenth of it, i.e. 30 seconds. Also, the edge main thread only checks every other 30 seconds (`N2N_RESOLVE_CHECK_INTERVAL`) for changes from the resolver thread.

However, if you set `N2N_RESOLVE_INTERVAL`  to a lower value, e.g. 30 seconds, you would probably get the same amount of DNS queries (depends on your system if they get handled locally or translate into actual DNS queries) than before, most of them are unnecessary because the IP address usually does not change that often.

> In the case of using domain name, if supernode does not respond, resolve the domain name first and then connect.

Thank you, this actually is a really good idea!!

I will implement it in a way that the resolver thread pushes up the next resolve should the supernode not be available. This however will require more wake-ups in between (to check for the need of an early DNS query requirement).

**Comment by small-5** [comment]
My supernode is running on the router.The router uses PPPoE. If redial, the IP will change.The TTL of my DDNS is 10, so the domain name change will take effect soon.I think the scheme I proposed should be able to deal with this problem perfectly,and there is no need to modify n2n_ RESOLVE_ INTERVAL.

**Comment by Logan007** [comment]
> I think the scheme I proposed should be able to deal with this problem perfectly

:100:

> ,and there is no need to modify n2n_ RESOLVE_ INTERVAL.

Well, the sleep and check intervals now change dynamically depending on the current state (resolver error, resolve requests).

**Comment by small-5** [comment]
Thank you!
