### ISSUE TITLE
May edges directly contact each other behind a NAT device?

### ISSUE THREAD

**Issue by twursc** [ntop/n2n#745]
Environment: 
```
edge1 ---    102.1.1.0       103.1.1.0                  edge4
edge2 ----------------- nat ------------- supernode --- edge5
edge3 ---         eth0       eth1                       edge6
```
6 edges and supernode have public addresses. 
But for some reason, some edges (1-3) connect to supernode via a nat device which will masquerade all traffics' src address to it's public address (eg: 103.1.1.10), so traffic betwen edges 1-3 will go through the supernode (tested). 
Is that any way to make these three nodes contact via it's public address directly but not via the supernode? such as announcing it's own public address to other edges, or allow specifying edge1's address on other edges' side.

**Comment by Logan007** [comment]
Are public IP address and internal IP address (to NAT) assigned to the same network interface? n2n currently binds to all (ANY) interfaces. So, binding to specific network interface could help it – to be implemented.

Other than that, I only could think of adding / modifying specific routes to the supernode at the edges 1 to 3 – stipulating the interface `dev` and (public) source address `src` of the edges for traffic to the supernode. If the supernode then sees the real public addresses of the edges 1 to 3, it will communicate those to the other edges, they should find each other then.

> But for some reason ...

If that reason is the firewall of edges 1 to 3 not allowing UDP connections once initiated changing communication partner, you need to check the firewall settings.

**Comment by twursc** [comment]
Edges 1-3 actually connects to NAT via it's public IP address, not internal, 
It's just because direct connection from edge 1-3 to 4-6 is bad so I use a NAT gateway as a forwarder.

**Sorry for the environment above is not clear enough, additional information:**
1. All edges have public IPs,
2. Edge 1-3 is in region 1,   Supernode & Edge 4-6 is in another region
2. Supernode has pub-ip 198.10.0.1
3. NAT has pub-ip at eth0 102.1.1.50 (for connecting edge 1-3),   pub-ip at eth1 103.1.1.50 (for connecting supernode and edge 4-6)
4. NAT mapped supernode's port 198.10.0.1:7777 (at eth1) to 102.1.1.50:9999 (at eth0), and this NAT gateway will also translate the source address
5. edge 1-3 connecting supernode via 102.1.1.50:9999

The question may be my NAT translated real public IP of edge 1-3 to it's public IP (eth1 - 103.1.1.0), so my supernode don't know the original addresses, edges 1-3 also cannot get other's real address.

**Comment by Logan007** [comment]
Oh, I see. You would need an additional supernode in region 1 then. It could run at one of the edges 1 to 3. It can be [federated](https://github.com/ntop/n2n/blob/dev/doc/Federation.md) with the original supernode, just give them both the same federation name `-F` and provide the other supernode's IP address (or, the mapped NAT) and port using `-l`.

As edges 1 to 3 are presumably very close to that new supernode then, you can make sure that they connect to that one: Just compile them with the [RTT option](https://github.com/ntop/n2n/blob/dev/doc/Building.md#federation--supernode-selection-by-round-trip-time).

Edges 4 to 6 will receive the public addresses of edges 1 to 3 and will at least **try** to connect to them. If that does not work, they will forward the traffic via "their" supernode (which will forward it to the federated supernode which will forward it then to the edges 1 to 3). Also, the edges will try to ping the new supernode from time to time. If you want to prevent those bad connections, you might want to route edge 1 to 3's public IP addresses to blackhole, i.e. `ip route add blackhole <edge1 IP>` at edge 4 to 6. You will see some error messages in the edge's log then indicating an "invalid argument" which is due to the blackhole.

Let us know how it works.

**Comment by twursc** [comment]
I have deployed another supernode on the left side and tried federation, it works.

**Comment by Logan007** [comment]
Considered answered, please re-open if required.
