### ISSUE TITLE
When n2n_v3 comes, can we reduce some of the options?

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#779]
In order to achieve future backward compatibility, it is suggested to remove some options which are not commonly used and are too difficult to use, and then let them out when they're ripe. for example,
-T / D / i / L 

Some parameters can be merged,
A1 / A2-A5

It's just a proposal, can be ignored, and I don't want to talk about it again.

**Comment by lucktu** [comment]
Some of the parameters also try to keep up with the old habits,
e --> L
p(sn) --> l

**Comment by Logan007** [comment]
> It's just a proposal

Honestly, I love proposals!

> I don't want to talk about it again.

Not wanting to start a whole new discussion...

> Some of the parameters also try to keep up with the old habits

... I just want to make a few points concerning the reasoning which have led to the current command line option scheme:

To prepare merging the supernode and edge executables in 4.0, I want the edge and supernode options to be in line, e.g. `-l` to provide supernode information to both, edge and supernode. And `-p` to provide the explicit port the program, edge and supernode, bind to. That is the reason why we have changed supernode's former `-l` to `-p`. This small change already brought up some users because it broke old habits – which I totally understand.

`-L` has already been taken by REGISTER's TTL setting. I do not want to have users change things to which they are customized again. So, the here newly added feature for preferred socket cannot get the `-L` to which some might be used coming from another fork. So, we have chosen the new `-e` which can be seen as concession to the loyal users of ntop's n2n who shall not be confused again.

> it is suggested to remove some options which are not commonly used and are too difficult to use, and then let them out when they're ripe. for example
> -T / D / i / L

These admittedly are expert settings. If we had graphical setup, I would hide them on an extra tab. As far as I can see, these options still are working properly and my best guess is that some users require those to get n2n working. **Please, everybody**, let us know about your needs.

> Some parameters can be merged
> A1 / A2-A5

I am not sure if I understand correctly. How should we merge them?

**Comment by lucktu** [comment]
In help, A1 / A2-A5

**Comment by lucktu** [comment]
Well, now that you know, I'm shutting it down
