### ISSUE TITLE
Use lzo or remove it

### ISSUE THREAD

**Issue by emanuele-f** [ntop/n2n#91]
minilzo is currently compiled but never used

**Comment by Logan007** [comment]
I would love the idea to use some kind of compression.

**Comment by Logan007** [comment]
This [example](https://fossies.org/linux/lzo/minilzo/testmini.c) gives well documented hints on how to use minilzo. 

However, we should take care of incompressible data (OUT_LEN >= IN_LEN) and do without compression in that case, i.e. send the original data. How to flag packets that are (not) compressed? Maybe bit 7 of the byte-sized version field?

Also, compression destination buffer size "OUT_LEN" must be larger than "IN_LEN" N2N_PKT_BUF_SIZE, namely `#define OUT_LEN     (IN_LEN + IN_LEN / 16 + 64 + 3)` according to line 55 of the example. Calling `.fwd` and `.rev` in `edge_utils` should be adopted accordingly.

**Comment by Logan007** [comment]
Making up my mind, I guess it would not be a good idea to publicly indicate payload characteristics, i.e. if it is compressed or not. A much better idea would be to use bit no. 7 of the padding length byte at the end of the payload. That way, the decode function can determine after decryption whether an additional deflate step is required or not.

**Comment by Logan007** [comment]
Please find attached a [patch](https://github.com/ntop/n2n/files/3238490/compression.txt).

**Comment by emanuele-f** [comment]
Using the padding field like this is a bit hacky

**Comment by Logan007** [comment]
Another way to see it is that technically, bit 7 to 4 are not used and still available...  And it saves a dedicated byte field.

**Comment by Logan007** [comment]
We could also indicate compression using the version field filled with a dedicated aes version number. Maybe `2` could stand for "_a compressed version `1`_" (or `0` and `1` respectively if reconsidering #150)?

**Comment by emanuele-f** [comment]
Compression should be a separate field. An host can receive compressed packets but send uncompressed packets

**Comment by Logan007** [comment]
Maybe a `compression_version` field directly after the `aes_version` field? The `compression_version` field could indicate what compression, e.g. compression method and strength, are used and need to be applied after decryption. For outgoing packets, there could be a `#define` just as with the `aes_version`. An 8-bit field should be big large enough in size?

**Comment by Logan007** [comment]
...the field should be part of the encrypted payload, though (see [above](https://github.com/ntop/n2n/issues/91#issuecomment-497091314)) - not giving any hints on payload characteristics.

**Comment by Logan007** [comment]
Would that be something to consider for 2.6? That way, we would have at least the option for future versions without the need to change aes packet format again - at least not for that feature. Let me know, I could prepare a pull request.

**Comment by Logan007** [comment]
PR #172

**Comment by emanuele-f** [comment]
This should be postponed after the 2.6 release. The following things should be also kept in mind:

- We should try to move standard operations (e.g. compression, hash-sign, replay protection) out of specific encryption modules (e.g. compression could be used by both twofish and aes). We should not mix AES code with minilzo code.
- We should add a cli option to disable compression and also a `configure` option to disable compression code compilation
- It may be better to link against a system-wide compression library if available
- A peer should send compressed packets only if it has verified that the other peer supports compression (e.g. via the peer_info)

**Comment by Logan007** [comment]
Dear Emanuele, 

Thank you for your feedback.

- I agreee that the compression code should be used more universally and in a more general place. `edge_utils.c` might be suitable - in fact, there has been a corresponding place-holding comment (line 1258).

- Concerning the cli option, I am completely with you. 

- With a view to `configure` options and the `peer_info`, I still am pondering your [comment](https://github.com/ntop/n2n/issues/91#issuecomment-507055896) on the receiver: It should always be able to decompress packets. Usually, compression is costly in terms of CPU. We should look for an algorithm which gives good compression ratio on reasonable CPU load _(easy for workstations)_ and which is extremly lightweight for decompression _(if neccessary, still being handled by smaller nodes like routers - they do not need to compress if forwarding as every node understands uncompressed packets - this would result in half of the bandwidth savings because it is for one way only - but also   saved the more costly de/encryption steps)_. Currently, I am (re-)implementing such an asymmetric compression algorithm (puCrunch), I will present results somewhen later. For now, it looks as if it is more than just comparable to zlib and others - especially having common packet sizes and performance in mind.

I do not see any problem postponing the implementation of compression. I will close the pull request as it does not meet the requirements of universality and generality. We could leave this issue open for further compression discussion.


Best regards,
Logan

**Comment by Logan007** [comment]
Backpedaling a moment and reflecting on my still ongoing compression experiment [`pucr`](https://github.com/Logan007/pucr), I found that _speed_ is a seemingly elusive aim... 

Even though I was extremely happy with 45 M**B**/s decompression speed on Raspberry Pi 3B+, it is with great admiration that I noted `lzbench -ezstd ivanova.bin`'s results of around 200 M**B**/s decompression speed. More than enough of a reserve for a gigabit ethernet connection to serve (which is limited to USB speed of 480 M**b**/s on Raspberry up to and including model 3 anyway, but that's another story).

It is not as much as `lzbench -elzo ivanova.bin`'s 320 M**B**/s, but `zstd`'s compression ratio is way, way better.

So, I wonder if we shouldn't just use `zstd` as new default to `n2n`. It is [praised](https://en.wikipedia.org/wiki/Zstandard#Features) as having reached the current Pareto frontier. It is licensed under a dual license (BSD + GPL2). I am not sure if we could use its source code under the GPL2 in `n2n` being GPL3. In any case, it should be safe to use it as (user- or system-installed)  library. By the way, Arch Linux' packet management switched from `xz` to `zstd` recently. 

I still think that compression might be helpful to make better use of resources – especially, when bandwidth is an issue or even the most determining factor. Shall we go for a test implementation of `zstd` in `n2n`? Let me know, I might volunteer.

However, I will continue my work on `pucr` which may not be on par with the fastest yet but reaches  better compression ratio at least in some cases... :smile:

**Comment by Logan007** [comment]
Please find attached this [patch](https://github.com/ntop/n2n/files/4143313/n2n-zstd.txt) to include `zstd` compression with AES encryption if installed.

After issuing the `patch -p1 < n2n-zstd.txt` command, a complete rebuild is required, i.e. `./autogen.sh` , `./configure` and `make`.

The chosen default compression level of `10` already offers decent compression for compressible data. The value ranges between `1` and `22` being the strongest compression level. It can easily be altered by changing the `ZSTD_COMPRESSION_LEVEL` definition added to `transform_aes.c`'s header.

Even though it already works quite well, this quick and dirty proof of concept is just intended for testing. A more comprehensive implementation needs to wait for the header format to be specified (#198) along with a more general packet assembly process.

**Comment by Logan007** [comment]
Tiny update to the `zstd` [patch](https://github.com/ntop/n2n/files/4155201/n2n-zstd.txt): removed unnecessary calls to `malloc`, `free` as well as `zstd`'s buffer size determination.

Some quick evaluation shows that link throughput (in my not too representative setup) seems to decrease by roughly 6 % due to compression. This was tested on desktop equipment attached to an extremely under-worked link using non-compressible data. Any different experience?

Bandwidth savings depend on how compressible the transmitted data is. `./edge --your-parameters-go-here-- -vvvv | grep compress` might help to get some indication. Huge savings on text-containing data and alike! :smile:

**Comment by Logan007** [comment]
Wouldn't the `Flags` field in the header be an appropriate, less hacky place to indicate compression? That way, we could use compression for all three transforms and implement it in `edge_utils.c` near the corresponding placeholder in line 1294; decompression accordingly.

This could quickly be implemented, long before #198 will be solved.

Now the question is what compression to use? `minilzo` or `zstd` or anything else? `zstd` would depend on an external library as long as it is not included with `n2n`. Are we allowed to take it in? At this point, I still am not sure if we could use its source code under the GPL2 in `n2n` being GPL3. Any idea on this?

If there are no objections, I could prepare a quick pull request using `minilzo` for now.

_P. S._ In the long term, we need to encrypt the header, not to publicly advertise payload characteristics.

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/n2n/pull/237
