### ISSUE TITLE
Using the BitTorrent DHT network for supernode, possible?

### ISSUE THREAD

**Issue by sweihub** [ntop/n2n#932]
Hi You Great Guys

Is it possible to use the popular BitTorrent DHT network as the supernode?

1. Each edge node announce an identical info-hash, maybe the hash of (community + something-else)
2. Each edge node join the DHT network, and query for the info-hash, it should returns a list of peers (our edges)
3. Now the peers (edges) should know each other

Here's a great & tiny DHT project might work.
https://github.com/jech/dht

Testing
```
./dht-example -4 6881 \
        dht.libtorrent.org 25401 \
        router.bittorrent.com 6881\
        router.utorrent.com 6881 \
        dht.transmissionbt.com 6881 \
        dht.aelitis.com 6881
```

trigger a dht search of hash,  change the hash in the dht-example.c might give you more peers, indescribable hash: `34C72FBF622E254ADE5DB11354CE7773ECEEA123 `
```
kill -SIGUSR2 `pidof dht-example`
```

By doing this, we don't need the standalone supernode anymore, we just use the BitTorrent DHT network as supernode, since most users do not have dedicated internet servers, and the DHT network is more robust.

Some DHT bootstrap nodes
```
dht.libtorrent.org 25401
router.bittorrent.com 6881
router.utorrent.com 6881 
dht.transmissionbt.com 6881 
dht.aelitis.com 6881
```

**Comment by Logan007** [comment]
Hello,

thanks for proposing that interesting idea. We indeed plan to switch to a more p2p-like approach and have already discussed some early ideas at some older issues.

If I understand your idea correctly, it would replace the directory function of the supernode. But how does it cover the other functions mentioned [here](https://github.com/ntop/n2n/issues/920#issue-1091665760)?

For the sake of scalability, up to now, edges only memorize the actually and currently used connections (other edges) and forget about them as soon as the corresponding connection orphans. Edges do not keep a full directory.

Currently, apart from Internet connection, n2n does neither require any pre-requisites nor have any major dependencies. I am not sure if we should rely on external services such as other DHT networks and their availability – especially as those often get blocked.

But that's something to be discussed. I am looking forward to it!

**Comment by sweihub** [comment]
Dear Mr. Logan007

Thank your for your thoughtful response, I didn't realize current supernode has more jobs than I thought,  N2N is really the 
 most outstanding P2P VPN ever, and it's still under active developing, thank you guys for the amazing works and contributions.

I just read the N2N-Vision and I was excide about it,  I am using N2N for network penetration simply because my home NAS has no internet IP, so an internet-required-supernode just blocks me a bit from original requirements, I think most users have such confusion, so a ready-to-use "internet supernode free services" will be welcome.

I agree with your saying that N2N should not rely on external service (BitTorrent DHT)， so could it be an option?

My ideas: 
1. The N2N works at OSI layer 3, the supernode is actual a virtual router, Internet address can be an option
2. We extract the hole-punching service as a flexible service, it can be a built-in with internet supernode, or an external hole-punching node/cluster, the service just enables the connectivity of (edges + supernode/router)
3. The hole-punching service node/cluster can be contributed by N2N users, no routing traffic, just for hole punching purpose, and the network can use the same algorithm as mainline DHT (Kademlia-based DHT),  and even the same protocol.

The changes can be minimal, the internet supernode built with hole-punching service can compose a DHT network if the users are willing to contribute,  for those without internet address, their (edge + supernode) will connect to the services for hole-punching.

**Comment by Logan007** [comment]
Thank you very much for sharing your ideas!

> I think most users have such confusion, so a ready-to-use "internet supernode free services" will be welcome.

For testing, ntop offers a small public supernode, please see the README file.

> The N2N works at OSI layer 3, the supernode is actual a virtual router, Internet address can be an option

We currently are on layer 2 to offer a virtual ethernet jack. I know that some users value this a lot. You can always run IP over an ethernet connection, even over a virtual one. From your point of view, what would be the advantage of going layer 3?

> We extract the hole-punching service as a flexible service, it can be a built-in with internet supernode, or an external hole-punching node/cluster, the service just enables the connectivity of (edges + supernode/router)

> The hole-punching service node/cluster can be contributed by N2N users, no routing traffic, just for hole punching purpose, and the network can use the same algorithm as mainline DHT (Kademlia-based DHT), and even the same protocol.

Some of n2n protocol's components have similarities to other protocols such as STUN. The good thing about n2n is to have it all bundled together, ready to run. On the other hand, it is a bit hard to separate the hole punching from packet forwarding here, mainly because the data packets already have a role in the hole punching process – even when just forwarded. I currently am not able to see a feasible way how to separate these. Are you aware of how the protocol works [in detail](https://luca.ntop.org/n2n.pdf)?

> I agree with your saying that N2N should not rely on external service (BitTorrent DHT)， so could it be an option?

As packet forwarding and hole punching are bundled so strongly, I do not see how we can use external services for parts of it.

However, there might be an interesting approach of putting information about available supernodes in some DHT network or other internet places, download it, extract it and provide it to the edges via the `-l ...` parameters. Every edge can take several supernodes. But for now, that would need to be done with CLI tools. And you are on your own with this. 

Also, if it is not the user who provides the supernodes, you should make sure to use at least header encryption `-H` if not full user authentication, please see the advanced documentation for further details about this.

**Comment by Logan007** [comment]
considered answered, please re-open if required
