### ISSUE TITLE
Is edge node number in a community limited?

### ISSUE THREAD

**Issue by readykevin** [ntop/n2n#959]
Hello, how many edge nodes can join a community? I try to use 5 edge nodes, it's ok. But I'm afraid a super node cannot support too many edge nodes.

**Comment by Logan007** [comment]
It only depends on your hardware and network capacities. About how many edges are you thinking then?

**Comment by readykevin** [comment]
when the number of edge nodes reach 1000, can the network system perfom well? will the hardware of supernode be a performance bottleneck?

**Comment by Logan007** [comment]
Hard to say, I have not tried that many, you might want to deploy additional supernodes for your network then, see [`doc/Federation.md`](https://github.com/ntop/n2n/blob/dev/doc/Federation.md).

Also, it will depend on how successful p2p is between your edges – because, if not successful, the supernodes additionally have to forward the traffic.

**Comment by readykevin** [comment]
> It only depends on your hardware and network capacities. About how many edges are you thinking then?

depends on supernode's or edgenode's ?

**Comment by readykevin** [comment]
Thanks.

**Comment by Logan007** [comment]
edge-wise, it will depend on how accessible the edge is for p2p – because direct p2p will not be forwarded through the supernode.

supernode-wise, the CPU needs to do the packet-handling and maybe perform some encryption if used with federated supernodes and/or encrypted header communities. The network bandwidth of the supernode might be a factor to handle the amount of traffic (registration traffic, broadcast traffic such as ARP protocol, forwarded traffic in case no p2p between the edges).

Federated supernodes however would share this load.
